<?php 

$addresses = [

    ['addressable_id' => 189, 'zipcode' =>'41810110', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Guillarda Muniz, 175 apt° 902'],
    ['addressable_id' => 447, 'zipcode' =>'41613900', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jaguaribe', 'address'=>'R da Fauna, 449 -Cd.Vereda do Sol Res-Alam.Jupiter 175'],
    ['addressable_id' => 7, 'zipcode' =>'41815300', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara ', 'address'=>'R AFONSO RUY DE SOUZA'],
    ['addressable_id' => 456, 'zipcode' =>'42700000', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Portão', 'address'=>'Estr do Coco, Km 5,5 - Cd Enc das Águas Qd. C Lt 27'],
    ['addressable_id' => 331, 'zipcode' =>'41830270', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Piauí, 213 apt  1101 - Ed. Ilhabella'],
    ['addressable_id' => 225, 'zipcode' =>'41830900', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'EDIBA-Av. Antônio Carlos Magalhães, 1113'],
    ['addressable_id' => 441, 'zipcode' =>'41650315', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã', 'address'=>'Al das Samambaias, 375  cs-04 Cd. Vila dos Ipês'],
    ['addressable_id' => 186, 'zipcode' =>'41810670', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Carme Miranda 120, Aptº 801, Ed. Jardim do Vale'],
    ['addressable_id' => 129, 'zipcode' =>'41830580', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R JOA0 BIAO DE CERQUEIRA, 306 APT 1102 A'],
    ['addressable_id' => 248, 'zipcode' =>'41720025', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Imbuí', 'address'=>'R Alberto Fiuza, 270 Com Morada Pq I, Edf. Itanhangá Tenis, apt 301'],
    ['addressable_id' => 62, 'zipcode' =>'40155250', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jardim Apipema', 'address'=>'R Sabino Silva, 919/ 1501 - Ed. Palais Atlantique'],
    ['addressable_id' => 393, 'zipcode' =>'41810030', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Alexandre de Humboldt, 137 ap 1102'],
    ['addressable_id' => 142, 'zipcode' =>'41810710', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Engº Adhemar Fontes, 254 aptº 202'],
    ['addressable_id' => 290, 'zipcode' =>'41815215', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Dr Hosannah Oliveira, 153 ap 1402'],
    ['addressable_id' => 220, 'zipcode' =>'42700000', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Vilas do Atlântico', 'address'=>'R Praia de Aratuba, Qd. 17 Lt 16'],
    ['addressable_id' => 315, 'zipcode' =>'41830451', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Ceará, 356 ap 602 - Ed Royal Garden'],
    ['addressable_id' => 73, 'zipcode' =>'40296250', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Candeal', 'address'=>'R Dr Alberto Pondé, s/n ap 401'],
    ['addressable_id' => 165, 'zipcode' =>'41810001', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Av Paulo VI, 2240, Edf. Pedranova, Apt 1001'],
    ['addressable_id' => 340, 'zipcode' =>'41650010', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã', 'address'=>'Av Orlando Gomes-Cd.Costa Verde R.L cs 12C'],
    ['addressable_id' => 304, 'zipcode' =>'41810000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Av Paulo VI, 2609 apt 601 Ed MansãoItaigara A'],
    ['addressable_id' => 143, 'zipcode' =>'41810001', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'Av Paulo VI, 2174 apt 401'],
    ['addressable_id' => 294, 'zipcode' =>'41830451', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Ceará, 256 aptº 1002 B Cond Vila Romana'],
    ['addressable_id' => 213, 'zipcode' =>'41830580', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R João Bião Cerqueira, 306 Apto 503 C,SSA'],
    ['addressable_id' => 469, 'zipcode' =>'41810600', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Dr Eduardo Bahiana, 181 ap 2201'],
    ['addressable_id' => 392, 'zipcode' =>'41830498', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Tenente Fernando Tuy,171 Aptº 1002'],
    ['addressable_id' => 89, 'zipcode' =>'41815330', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Hermann Neeser, 111 casa'],
    ['addressable_id' => 371, 'zipcode' =>'40080001', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Vitória', 'address'=>'Av 7 de Setembro, 2438 apt 304'],
    ['addressable_id' => 278, 'zipcode' =>'41830492', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Altino Serbeto de Barros, 295/ 702 - Ed Maison Montparnesse'],
    ['addressable_id' => 180, 'zipcode' =>'41810670', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Carmen Miranda, 120 aptº 401'],
    
    ['addressable_id' => 11, 'zipcode' =>'40130030', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Barra', 'address'=>'Av Princ Isabel, 709/201'],
    ['addressable_id' => 512, 'zipcode' =>'42700000', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Vilas do Atlântico', 'address'=>'Av Praia de Guarujá, 420 Q.d E6 Lt 6'],
    ['addressable_id' => 253, 'zipcode' =>'41830600', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Colmar Americano da Costa, 199 apt  802'],
    ['addressable_id' => 24, 'zipcode' =>'41830315', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Renato de Menezes Berenguer, 80 / 404'],
    ['addressable_id' => 257, 'zipcode' =>'40130030', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Barra Avenida', 'address'=>'Av Princesa Isabel, 695 apt 1101 Ed. Bretagne'],
    ['addressable_id' => 434, 'zipcode' =>'41600160', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Stella Maris', 'address'=>'Alameda Praia de Itacaré, 106 casa 2'],
    
    ['addressable_id' => 338, 'zipcode' =>'41810820', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Manoel Gomes de Mendonça, 93 apt  1301 Cond. Pituba Ville'],
    ['addressable_id' => 442, 'zipcode' =>'41770395', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Stiep', 'address'=>'R Edístio Pondé, 65 aptº 502'],
    ['addressable_id' => 46, 'zipcode' =>'41250430', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Vale dos Lagos', 'address'=>'Al Oscar Cruz, 10 - Loteamento Vila Mariza'],
    ['addressable_id' => 113, 'zipcode' =>'48110000', 'state'=>'BA','city'=>'Catu', 'district'=> 'Rua Nova', 'address'=>'R Nailton Sandes, 66'],
    ['addressable_id' => 424, 'zipcode' =>'41603110', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Stella Maris', 'address'=>'R Jose Augusto T Dantas Cond Est do Sol Qd AB/4'],
    ['addressable_id' => 16, 'zipcode' =>'41830430', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Santa Helena, 158/1202 - Pituba'],
    ['addressable_id' => 179, 'zipcode' =>'41950160', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Rio Vermelho', 'address'=>'R Alexandre de Gusmão, 159 casa'],
    ['addressable_id' => 107, 'zipcode' =>'41720075', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Imbuí', 'address'=>'R Jayme Sapolnik, 1100 apt 304 T - 1 Ed Volare'],
    ['addressable_id' => 107, 'zipcode' =>'41720075', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Imbuí', 'address'=>'R Jayme Sapolnik, 1100 apt 304 T - 1 Ed Volare'],
    ['addressable_id' => 270, 'zipcode' =>'41613100', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã', 'address'=>'R Haeckel José Almeida-Cd.Jd Piatã, Qd 3 Lt 12'],
    ['addressable_id' => 471, 'zipcode' =>'41815010', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Edith M de Gama Abreu, 300 ap 801'],
    ['addressable_id' => 219, 'zipcode' =>'40265020', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Santa Tereza', 'address'=>'R Hélio de Oliveira, 286 / 101 Ed. Emidio'],
    ['addressable_id' => 53, 'zipcode' =>'48005420', 'state'=>'BA','city'=>'Alagoinhas', 'district'=> 'Centro', 'address'=>'R Aderivaldo Gabriel Junior, 50'],
    ['addressable_id' => 384, 'zipcode' =>'42700000', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Portão', 'address'=>'Av Santos Dumont - Cond. Vilas do Bosque, Qd D, Lt 2'],
    ['addressable_id' => 23, 'zipcode' =>'41830630', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Dr Antonio Monteiro, 105 ap 901 Ed igaratim'],
    ['addressable_id' => 509, 'zipcode' =>'42840000', 'state'=>'BA','city'=>'Camaçari', 'district'=> 'Catu de Abrantes', 'address'=>'Estr do Coco, Km 11 Q 51 Lt 07 Cd Alph. Lit Norte1'],
    ['addressable_id' => 261, 'zipcode' =>'41650680', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã', 'address'=>'R Eng.Erociano da Cruz Neves Jd.Placaford, R B cs 82'],
    ['addressable_id' => 158, 'zipcode' =>'41820380.', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Caminho das Árvores', 'address'=>'R do Tarumã, 30,Ap. 801'],
    ['addressable_id' => 227, 'zipcode' =>'41810001', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Av Paulo VI, 2200/ 1002'],
    ['addressable_id' => 356, 'zipcode' =>'40040280', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Nazaré', 'address'=>'Largo Campo da Pólvora, 18/ 201'],
    ['addressable_id' => 25, 'zipcode' =>'41810001', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Av Paulo VI, 2174 ap 1301'],
    ['addressable_id' => 473, 'zipcode' =>'41830510', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Machado Neto, 281 ap 902-B'],
    ['addressable_id' => 312, 'zipcode' =>'41815200', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R João da Silva Campos, 325'],
    ['addressable_id' => 102, 'zipcode' =>'41940040', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Rio Vermelho', 'address'=>'R Tamoios, 213/1301 Ed. Blanche'],
    ['addressable_id' => 170, 'zipcode' =>'40293200', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Cidade Jardim', 'address'=>'R Al dos Jasmins, 141/ 501- Edf. Mansão Bque Mangueiras'],
    ['addressable_id' => 199, 'zipcode' =>'40296220', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Candeal', 'address'=>'R Carlos Maron, 62/ 701'],
    ['addressable_id' => 254, 'zipcode' =>'41760160', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Costa Azul', 'address'=>'R Ce. Durval Mattos, 835 ap 202'],
    ['addressable_id' => 198, 'zipcode' =>'41750103', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jardim Armação', 'address'=>'R Rio Lena, 65 ap 1204 - Ed. Bela Vista'],
    ['addressable_id' => 166, 'zipcode' =>'42841000', 'state'=>'BA','city'=>'Camaçari', 'district'=> 'Busca Vida', 'address'=>'Est Coco - KM 08 Cd.Pamplona - 13-A'],
    ['addressable_id' => 385, 'zipcode' =>'41810425', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Clara Nunes, 310/602 Cond. Pituba Boulevard'],
    ['addressable_id' => 353, 'zipcode' =>'41810425', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Clara Nunes, 310 / 402'],
    ['addressable_id' => 176, 'zipcode' =>'41760110', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Costa Azul', 'address'=>'R Prof Cassilandro Barbuda, 331 ap 101'],
    ['addressable_id' => 8, 'zipcode' =>'41651050', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã', 'address'=>'R Deraldo Motta,CdVeredasSol, Al Saturno cs179'],
    ['addressable_id' => 504, 'zipcode' =>'41950800', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Vale das Pedrinhas', 'address'=>'R Temistocles, 78'],
    ['addressable_id' => 327, 'zipcode' =>'41260195', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Canabrava', 'address'=>'Al Mata Atlantica II, B-22, ap 002'],
    ['addressable_id' => 389, 'zipcode' =>'41815370', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Slvio Valente, 89 ap 902'],
    ['addressable_id' => 83, 'zipcode' =>'41483100', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Alphaville 2', 'address'=>'R das Apineas, 714 Alphaville Salvador2'],
    ['addressable_id' => 42, 'zipcode' =>'41815210', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Artesão João da Prata, 154 ap 1402'],
    ['addressable_id' => 437, 'zipcode' =>'40296320', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Cidade Jardim', 'address'=>'R Guilhermino de Freitas Jatoba, 80 ap 1402'],
    ['addressable_id' => 314, 'zipcode' =>'41830903', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Altino Serbeto de Barros, 345 ap 703'],
    ['addressable_id' => 3, 'zipcode' =>'40270010', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Vila Laura', 'address'=>'R Raul Leite, 1024 ap 02'],
    ['addressable_id' => 76, 'zipcode' =>'41810110', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Guillard Muniz, 211 ap 901'],
    
    ['addressable_id' => 175, 'zipcode' =>'40150080', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Graça', 'address'=>'Av Princesa Leopoldina, 270 ap 1701'],
    ['addressable_id' => 155, 'zipcode' =>'41815270', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Wanderley Pinho, 735ap701'],
    ['addressable_id' => 141, 'zipcode' =>'41830120', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Espirito Santo, 234 apto 801'],
    ['addressable_id' => 149, 'zipcode' =>'40110160', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Canela', 'address'=>'R João das Botas, 283 apto 303 Ed Pegasus'],
    ['addressable_id' => 510, 'zipcode' =>'42700000', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Estrada do Coco', 'address'=>'Loteamento Vilas do Bosque, Lt 22 Qd Q'],
    ['addressable_id' => 174, 'zipcode' =>'41830315', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Renato de Menezes Berenguer, 80 apto 1003 B'],
    ['addressable_id' => 185, 'zipcode' =>'41720100', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Imbuí', 'address'=>'R Das Patativas, 400 casa 03'],
    ['addressable_id' => 239, 'zipcode' =>'41741572', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituaçu', 'address'=>'R Lima Borges, 225 casa 3'],
    ['addressable_id' => 365, 'zipcode' =>'42711610', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Caji', 'address'=>'2a. Travessa Dr.Gerino de souza F, 158'],
    ['addressable_id' => 116, 'zipcode' =>'41815215', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Dr Hosannah de Oliveira, 40 ap103'],
    ['addressable_id' => 79, 'zipcode' =>'41830630', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Hilton Rodrigues, 358 ap 904'],
    ['addressable_id' => 2, 'zipcode' =>'42801050', 'state'=>'BA','city'=>'Camaçari', 'district'=> 'Catu de Abrantes', 'address'=>'Estr do Coco, KM8, 03, Qd-1 Lt7 CD Busca Vida'],
    ['addressable_id' => 275, 'zipcode' =>'41650230', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã', 'address'=>'Al das Samambaias, 619 cs 39'],
    ['addressable_id' => 81, 'zipcode' =>'40285600', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Brotas', 'address'=>'Av Mario Leal ferreira, 341 ap 303 CdVale Flores'],
    ['addressable_id' => 324, 'zipcode' =>'41815000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R ALBERTO SILVA, 63 apt 301'],
    ['addressable_id' => 496, 'zipcode' =>'41820680', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Caminho das Árvores', 'address'=>'Al Dos Umbuzeiros, 445  ap 401'],
    ['addressable_id' => 30, 'zipcode' =>'42707760', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Vilas do Atlântico', 'address'=>'R PRAIA DE MAGUINHOS, 10'],
    ['addressable_id' => 301, 'zipcode' =>'41613020', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jaguaribe', 'address'=>'Rua Almir Tourinho, 14, JD Gantois'],
    ['addressable_id' => 208, 'zipcode' =>'45840000', 'state'=>'BA','city'=>'Guaratinga', 'district'=> 'Centro', 'address'=>'R Joaquim Nabuco, 161'],
    ['addressable_id' => 137, 'zipcode' =>'41830451', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba ', 'address'=>'R Ceará, 526 apt 1102c '],
    ['addressable_id' => 264, 'zipcode' =>'40280000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Parque Bela Vista ', 'address'=>'Av ACM, 3359, apto 304 sul, Condomínio Residencial Torres do Iguatemi'],
    ['addressable_id' => 284, 'zipcode' =>'40425030', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Monte Serrat ', 'address'=>'R Rio Jaguaripe, 329, BL 8-B  Ap 102'],
    
    ['addressable_id' => 72, 'zipcode' =>'42701350', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Jardim Aeroporto', 'address'=>'R Doutor Barreto, 703, Cond  Ed R. Amp.'],
    ['addressable_id' => 163, 'zipcode' =>'40210650', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Federação ', 'address'=>'R Pe Camilo Torrend, 185 '],
    ['addressable_id' => 178, 'zipcode' =>'41830480', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba ', 'address'=>'Al da Pádua,407 Ed Resid Torre de Paula ap701'],
    ['addressable_id' => 342, 'zipcode' =>'41650230', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã ', 'address'=>'Al das Samambaias, 320 casa 24'],
    ['addressable_id' => 363, 'zipcode' =>'41830480', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba ', 'address'=>'Al Pádua, 407 ap 1201 '],
    ['addressable_id' => 391, 'zipcode' =>'41830498', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba ', 'address'=>'R Tenente Fernando Tuy, 30 ap 701-A'],
    ['addressable_id' => 467, 'zipcode' =>'41830020', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba ', 'address'=>'R Minas Gerais, 383 ap 802 '],
    ['addressable_id' => 123, 'zipcode' =>'41815320', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara ', 'address'=>'R Almeida Garret, 107 ap 604 Residencial Toulon'],
    ['addressable_id' => 217, 'zipcode' =>'40285840', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Acupe de Brotas ', 'address'=>'R Atacílio Santos, 242 ap 1606-HP'],
    ['addressable_id' => 358, 'zipcode' =>'41710040', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Boca do Rio ', 'address'=>'R Bernadete Dias, 25 1º andar'],
    ['addressable_id' => 369, 'zipcode' =>'41770160', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Stiep ', 'address'=>'1ª Tv. Arnaldo Lopes da Silva, 74 Ed Mar do Caribe - ap 1304'],
    ['addressable_id' => 377, 'zipcode' =>'41815000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara ', 'address'=>'R Alberto Silva, 108 ap 903 '],
    ['addressable_id' => 388, 'zipcode' =>'40220005', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Engenho Velho da Federação', 'address'=>'R Dr. Rômulo Serrano, 261 ap 804 Ed Palazzo di Tiberio'],
    ['addressable_id' => 433, 'zipcode' =>'41730101', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Paralela ', 'address'=>'Av Luis Viana 311, Cond. Le Parc - torre 9 ap 303'],
    ['addressable_id' => 435, 'zipcode' =>'41770395', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Stiep ', 'address'=>'R Edístio Pondé '],
    ['addressable_id' => 18, 'zipcode' =>'41741170', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituaçu ', 'address'=>'Trav. lbertino Cabral Henrique, 212 ap 1201'],
    ['addressable_id' => 31, 'zipcode' =>'42710400', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Buraquinho ', 'address'=>'R Ministro ACM, 447  bl 10 ap 203'],
    ['addressable_id' => 66, 'zipcode' =>'41810750', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba ', 'address'=>'R Alte. Ernestro Melo Jr, 106 ap 501'],
    ['addressable_id' => 192, 'zipcode' =>'41650002', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã ', 'address'=>'R Eng. Graciano da Cruz Neves 16/B '],
    ['addressable_id' => 193, 'zipcode' =>'41810100', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba ', 'address'=>'Rua das Margaridas, 239 apto 601 '],
    ['addressable_id' => 214, 'zipcode' =>'41760180', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Costa Azul ', 'address'=>'Ruas Prof. Isaias Alves, 266 apto23 B '],
    ['addressable_id' => 282, 'zipcode' =>'40150080', 'state'=>'BA','city'=>'Salvador ', 'district'=> 'Graça ', 'address'=>'Av. Princesa Leopoldina, 192 ap 702'],
    ['addressable_id' => 309, 'zipcode' =>'22221011', 'state'=>'BA','city'=>'Rio de Janeiro ', 'district'=> 'Catete ', 'address'=>'Rua Bento Lisboa, 120 bl 1 ap 901 '],
    ['addressable_id' => 410, 'zipcode' =>'41830480', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba ', 'address'=>'Alameda Pádua 470 ap 1703 '],
    ['addressable_id' => 65, 'zipcode' =>'41680050', 'state'=>'BA','city'=>'Salvador ', 'district'=> 'Patamares ', 'address'=>'R Bicuiba 573 Ed Giardino Reale '],
    ['addressable_id' => 70, 'zipcode' =>'40231250', 'state'=>'BA','city'=>'Salvador ', 'district'=> 'Federação ', 'address'=>'Av. Candeal da Silva, 330, apt 47 '],
    ['addressable_id' => 97, 'zipcode' =>'40230370', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Federação ', 'address'=>'R Eng Afonso Oliva, conj 16, bl C ap 201'],
    ['addressable_id' => 162, 'zipcode' =>'41680090', 'state'=>'BA','city'=>'Salvador ', 'district'=> 'Paralela/Patamares ', 'address'=>'R Lechamp 87 Ed Gardenia ap304'],
    ['addressable_id' => 241, 'zipcode' =>'40285040', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Brotas ', 'address'=>'Av. Dom João VI, 249, ap 151 '],
    ['addressable_id' => 276, 'zipcode' =>'41706670', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Boca do Rio ', 'address'=>'Av. Dom Eugênio Sales, 176 TO 01 ap 1108'],
    ['addressable_id' => 386, 'zipcode' =>'41810670', 'state'=>'BA','city'=>'Salvador ', 'district'=> 'Pituba ', 'address'=>'Rua Carmem Miranda, 49/1102 '],
    ['addressable_id' => 423, 'zipcode' =>'40275160', 'state'=>'BA','city'=>'Salvador ', 'district'=> 'Campinas de Brotas ', 'address'=>'R Campinas de Brotas, 399 Ed Peroba ap 04'],
    ['addressable_id' => 19, 'zipcode' =>'41815140', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara ', 'address'=>'R Delegado Walter Lino Drummond, 69, ap701 Ed Vega'],
    ['addressable_id' => 27, 'zipcode' =>'40285040', 'state'=>'BA','city'=>'Salvador ', 'district'=> 'Brotas ', 'address'=>'R Com Pereira da Silva,174 ap 603'],
    ['addressable_id' => 98, 'zipcode' =>'40295050', 'state'=>'BA','city'=>'Salvador ', 'district'=> 'Horto Florestal ', 'address'=>'Av. Santa Luzia, 610 Ed Ravello ap 2602'],
    ['addressable_id' => 110, 'zipcode' =>'41620770', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itapuã ', 'address'=>'Al N. Sra de Fátima,15'],
    ['addressable_id' => 354, 'zipcode' =>'41760050', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Costa Azul ', 'address'=>'R Dr Boureau 197 Ed. Saint Tropez'],
    ['addressable_id' => 493, 'zipcode' =>'41830270', 'state'=>'BA','city'=>'Salvador ', 'district'=> 'Pituba ', 'address'=>'R Piauí, 795 Res.Monte Pascoal ap 908'],
    ['addressable_id' => 286, 'zipcode' =>'41610720', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itapuã', 'address'=>'Terceira Travessa do Gravatá, 97'],
    ['addressable_id' => 136, 'zipcode' =>'41810680', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba ', 'address'=>'R Anthenor Tupinambá, 254 ap 201 Ed Mario F Souza'],
    ['addressable_id' => 450, 'zipcode' =>'42825901', 'state'=>'BA','city'=>'Camaçari', 'district'=> 'Catu de Abrantes ', 'address'=>'Estr do Coco, km 08 Busca Vida - Cd Pampalona Qd C Lt 01'],
    ['addressable_id' => 373, 'zipcode' =>'71940540', 'state'=>'DF','city'=>'Brasilia', 'district'=> 'Águas Claras', 'address'=>'R 18 Sul, Lote 13 apt 1001'],
    ['addressable_id' => 17, 'zipcode' =>'41650230', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã ', 'address'=>'Ala das Samambaias, 620 ap 107-BL 2'],
    ['addressable_id' => 470, 'zipcode' =>'41830300', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba ', 'address'=>'R Emilio Odebrecht, 254 ap 302 Cd Solar Palmeiras '],
    ['addressable_id' => 125, 'zipcode' =>'41830480', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba ', 'address'=>'Alameda Pádua, 407 ap 503 '],
    ['addressable_id' => 221, 'zipcode' =>'41830498', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba ', 'address'=>'R Tenente Fernando Tuy,192 apt 504'],
    ['addressable_id' => 145, 'zipcode' =>'41800700', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara ', 'address'=>'Av ACM, 1113 '],
    ['addressable_id' => 295, 'zipcode' =>'41830595', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba ', 'address'=>'Al Benevento, 177 Ed Flávio  ap 102'],
    ['addressable_id' => 421, 'zipcode' =>'41181100', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Cabula VI ', 'address'=>'R Anisio Melhor,77 bl 64 ap 102 '],
    ['addressable_id' => 408, 'zipcode' =>'40279435', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Parque Bela Vista', 'address'=>'Rua Senador Theotonio Vilela 256, casa 8'],
    ['addressable_id' => 262, 'zipcode' =>'40285001', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Brotas', 'address'=>'Av. Dom João VI, 378, Edf Ana Cristina apt 103'],
    ['addressable_id' => 313, 'zipcode' =>'41650472', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã ', 'address'=>'R Marcos Pinheiro, 69, bl 3 ap 101'],
    ['addressable_id' => 458, 'zipcode' =>'40450211', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Uruguay', 'address'=>'Rua do Uruguay, 331'],
    ['addressable_id' => 32, 'zipcode' =>'41192065', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Cabula', 'address'=>'Rua Amazonas, 78, Cond. Villa Arboretto, Tr 01, apto 1103'],
    ['addressable_id' => 43, 'zipcode' =>'40140000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Barra', 'address'=>'Av. Princesa Isabel, 600, Edf Santa Martha, apto 503'],
    ['addressable_id' => 45, 'zipcode' =>'41810820', 'state'=>'BA','city'=>'Salvador ', 'district'=> 'Pituba ', 'address'=>'R Manoel Gomes de Mendoça,307 ap702'],
    ['addressable_id' => 75, 'zipcode' =>'42701310', 'state'=>'BA','city'=>'Salvador ', 'district'=> 'Jardim Aeroporto', 'address'=>'R Dr. Barreto 203 ap 03 Cond Rec. Imperial '],
    ['addressable_id' => 96, 'zipcode' =>'41830480', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba ', 'address'=>'Alameda Pádua, 225 ap 1901'],
    ['addressable_id' => 112, 'zipcode' =>'41830630', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba ', 'address'=>'R Hilton Rodrigues, 152 ap 302'],
    ['addressable_id' => 114, 'zipcode' =>'41830475', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Rua Cícero Simões, 225 APT. 1101'],
    ['addressable_id' => 144, 'zipcode' =>'40155000', 'state'=>'BA','city'=>'Salvador ', 'district'=> 'Jardim Apipema ', 'address'=>'R Nita Costa, 145 ap 1202 '],
    ['addressable_id' => 146, 'zipcode' =>'41250579', 'state'=>'BA','city'=>'Salvador', 'district'=> 'São Marcos', 'address'=>'Cond. Bosque Imperial'],
    ['addressable_id' => 190, 'zipcode' =>'40290901', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Acupe de Brotas ', 'address'=>'Av D. João VI, 800 bl B ap 103 Cd Pátio Jardins'],
    ['addressable_id' => 191, 'zipcode' =>'41150000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Cabula ', 'address'=>'R Silveira Martins, 150 apt 1202 Ed Vivenda dos Lirios'],
    ['addressable_id' => 194, 'zipcode' =>'41815340', 'state'=>'BA','city'=>'Salvador ', 'district'=> 'Itaigara ', 'address'=>'R Érico Veríssimo, 137 ap702 '],
    ['addressable_id' => 207, 'zipcode' =>'40252020', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Cosme de Farias', 'address'=>'Rua Abelardo Palma, 83 C'],
    ['addressable_id' => 267, 'zipcode' =>'41830500', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Alameda Salerno, 113, 1102 B'],
    ['addressable_id' => 283, 'zipcode' =>'41830600', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba ', 'address'=>'R Colmac Americano da Costa, 483'],
    ['addressable_id' => 317, 'zipcode' =>'41192005', 'state'=>'BA','city'=>'Salvador ', 'district'=> 'Narandiba ', 'address'=>'Av Edgard Santos, 596 ap 203-B '],
    ['addressable_id' => 318, 'zipcode' =>'45208705', 'state'=>'BA','city'=>'Jequié ', 'district'=> 'Espírito Santo', 'address'=>'R N, URBIS IV, 09 '],
    ['addressable_id' => 348, 'zipcode' =>'42706100', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Ipitanga ', 'address'=>'R Milena Ramone Alencar Ramos, 222 casa 06 Cond. Vila Veneza'],
    ['addressable_id' => 351, 'zipcode' =>'41150000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Cabula', 'address'=>'R Silveira Martins, 95 ap 907 B'],
    ['addressable_id' => 362, 'zipcode' =>'40715500', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Ilha Amarela', 'address'=>'Rua Rio Sena nº11'],
    ['addressable_id' => 422, 'zipcode' =>'11030151', 'state'=>'BA','city'=>'São Paulo', 'district'=> 'Santos', 'address'=>'Rua Republica do Equador, 127, apto 142A'],
    ['addressable_id' => 440, 'zipcode' =>'41720000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Imbuí', 'address'=>'Rua João José Rescala, 198'],
    ['addressable_id' => 428, 'zipcode' =>'41830451', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Rua Ceará, 526, apto 1102 C'],
    ['addressable_id' => 462, 'zipcode' =>'41760110', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Costa Azul', 'address'=>'Rua Professor Cassilandro Babuda, nº 161 Edf. Tiberíedes apto 801'],
    ['addressable_id' => 480, 'zipcode' =>'41815150', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara ', 'address'=>'R Reitor Macedo Costa, 113 ap 1403B'],
    ['addressable_id' => 488, 'zipcode' =>'41820020', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Caminho das Árvores', 'address'=>'Av Tancredo Neves, 1160 ap 504'],
    ['addressable_id' => 122, 'zipcode' =>'40285000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Brotas', 'address'=>'Av Dom João VII, 275 ap 131 Ed Jurupari'],
    ['addressable_id' => 44, 'zipcode' =>'40150360', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Graça', 'address'=>'R Manoel Barreto, 349 apt 901'],
    ['addressable_id' => 249, 'zipcode' =>'41720000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Imbuí', 'address'=>'Rua João José Rescala, 210 - Vila Anaiti - Cond. Absolutto, ap 1606B'],
    ['addressable_id' => 334, 'zipcode' =>'41830530', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Rua Território do Rio Branco, 405, apto 1401 A'],
    ['addressable_id' => 503, 'zipcode' =>'41285360', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba ', 'address'=>'Av Antonio Carlos Magalhães, 1113'],
    ['addressable_id' => 397, 'zipcode' =>'41815320', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'Rua Almeida Garret, 107, ap 704'],
    ['addressable_id' => 33, 'zipcode' =>'41825903', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Av. Antonio Carlos Magalhães, 1113'],
    ['addressable_id' => 78, 'zipcode' =>'41150020', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Cabula', 'address'=>'Conj. Colina das Árvores, bl 193, ap 203'],
    ['addressable_id' => 272, 'zipcode' =>'40100000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'Av. Antonio Carlos Magalhães'],
    ['addressable_id' => 429, 'zipcode' =>'41320655', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Castelo Branco', 'address'=>'Rua 12, casa 13'],
    ['addressable_id' => 153, 'zipcode' =>'41815000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'Rua Alberto Silva, 108/903'],
    ['addressable_id' => 41, 'zipcode' =>'40110010', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Canela', 'address'=>'Rua Marechal Floriano, 524'],
    ['addressable_id' => 425, 'zipcode' =>'41825903', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Av Antonio Carlos Magalhães, 1113'],
    ['addressable_id' => 513, 'zipcode' =>'41825903', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara ', 'address'=>'Av. Antonio Carlos Magalhães, 1113'],
    ['addressable_id' => 111, 'zipcode' =>'41820700', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Caminho das Árvores', 'address'=>'Rua Clarival Prado Valladares, 71/apt204 N'],
    ['addressable_id' => 94, 'zipcode' =>'41760160', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Costa Azul', 'address'=>'Rua Coronel Durval Mattos'],
    ['addressable_id' => 28, 'zipcode' =>'41830498', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Rua Tenente Fernando Tuy, nº 56, Apto 604B'],
    ['addressable_id' => 119, 'zipcode' =>'41150000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Cabula ', 'address'=>'R Silveira Martins, Cond. Pomar do Cabula, BL 267, ap 508'],
    ['addressable_id' => 269, 'zipcode' =>'41741550', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituaçu', 'address'=>'Rua Manoel a. Galvão, 772, cs 02'],
    ['addressable_id' => 229, 'zipcode' =>'41741550', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituaçu', 'address'=>'Rua Manoel Antônio Galvão'],
    ['addressable_id' => 12, 'zipcode' =>'40150380', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Graça', 'address'=>'Rua Djalma Ramos, 590 apt 302B'],
    ['addressable_id' => 461, 'zipcode' =>'41098040', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Horto Bela Vista', 'address'=>'Alameda dos Jardins'],
    ['addressable_id' => 224, 'zipcode' =>'41815120', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'Rua Monsenhor Eugênio Veiga, 173 - apt 1202'],
    ['addressable_id' => 35, 'zipcode' =>'41924110', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Santa Cruz', 'address'=>'Rua Juthay Magalhães, nº 555'],
    ['addressable_id' => 485, 'zipcode' =>'41245020', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pau da Lima', 'address'=>'Av. Alioma Balleeiro, 96, Cond. Morada Bela, Ed Ouro, apto 304'],
    ['addressable_id' => 50, 'zipcode' =>'40155000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Ondina', 'address'=>'R Nita Costa, 382 apt. 302'],
    ['addressable_id' => 466, 'zipcode' =>'40150370', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Chame Chame', 'address'=>'Av Centenario, 3072 ap.402'],
    ['addressable_id' => 61, 'zipcode' =>'40080003', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Vitória', 'address'=>'Av 7 de Setembro, 2493 apt.401'],
    ['addressable_id' => 476, 'zipcode' =>'40144000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Barra Avenida', 'address'=>'Av Princesa Isabel, 542 apt 1301'],
    ['addressable_id' => 105, 'zipcode' =>'40155010', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jardim Apipema', 'address'=>'R Des Demétrio Tourinho, 168 apt 401'],
    ['addressable_id' => 157, 'zipcode' =>'40144000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Barra Avenida', 'address'=>'Av Princesa Isabel, 458 ap 301-Ed.OuroVelho'],
    ['addressable_id' => 77, 'zipcode' =>'41810710', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Rua Engenheiro Adhemar Fontes 293, condomínio Pituba Top, Ed. Alpes, Apto. 802'],
    ['addressable_id' => 95, 'zipcode' =>'40157150', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Chame-Chame', 'address'=>'Av Centenario, 41 apt 601 '],
    ['addressable_id' => 345, 'zipcode' =>'41815130', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Dr Antonio Monteiro, 228 /1003 -Ed.Alamo'],
    ['addressable_id' => 236, 'zipcode' =>'41830580', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Al Pádua, 59 s/103'],
    ['addressable_id' => 370, 'zipcode' =>'41770030', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Stiep', 'address'=>'R Arthur Fraga Cj ValeRios St, (STI.AP 02)'],
    ['addressable_id' => 492, 'zipcode' =>'41600670', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Stella Maris', 'address'=>'CJ Petromar-Via Local C-Vilage 552D-cs.1'],
    ['addressable_id' => 482, 'zipcode' =>'41820240', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Eng Adhemar Fontes, 293 / 301 -'],
    ['addressable_id' => 486, 'zipcode' =>'40150250', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Graça', 'address'=>'R Com. Horácio Urpia Jr, 68 ap 1301'],
    ['addressable_id' => 511, 'zipcode' =>'41830498', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Ten Fernando Tuy, 171 ap 501'],
    ['addressable_id' => 216, 'zipcode' =>'41830450', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Ceará, 473/ 602 -Ed V, dos Coqueiros'],
    ['addressable_id' => 430, 'zipcode' =>'41940340', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Rio Vermelho', 'address'=>'R Francisco Catharino pithon, 345 ap 101'],
    ['addressable_id' => 223, 'zipcode' =>'41830498', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Tenente Fernando Tuy, 56 ap  403 Ed JE'],
    ['addressable_id' => 121, 'zipcode' =>'41630395', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itapuã', 'address'=>'R Edmundo Loureiro, C-2A Jd Encantado'],
    ['addressable_id' => 6, 'zipcode' =>'40150480', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Graça', 'address'=>'R Flórida, 211 ap 903 - Ed. El Prado'],
    ['addressable_id' => 308, 'zipcode' =>'41603295', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Praia do Flamengo', 'address'=>'R Des Adolfo Leitão Guerra, 110 ap 2'],
    ['addressable_id' => 321, 'zipcode' =>'40150000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Graça', 'address'=>'R 8 de Dezembro, 137 apt 701'],
    ['addressable_id' => 379, 'zipcode' =>'40110010', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Canela', 'address'=>'R Mal. Floriano, 25 ap 1202 - Ed.SolarJoãoGoe'],
    ['addressable_id' => 115, 'zipcode' =>'40144000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Barra Avenida', 'address'=>'Av Princesa Isabel, 756 ap 603'],
    ['addressable_id' => 182, 'zipcode' =>'41815010', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Edith M Gama Abreu, 53 apt 603'],
    ['addressable_id' => 367, 'zipcode' =>'41810660', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Alte Carlos Paraguaçu de Sá, 140 1p 1202'],
    ['addressable_id' => 468, 'zipcode' =>'40110150', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Graça', 'address'=>'Av Araújo Pinho, 421 ap 604'],
    ['addressable_id' => 5, 'zipcode' =>'40155190', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jardim Apipema', 'address'=>'R Plinio Moscoso, 1074 apt 601'],
    ['addressable_id' => 246, 'zipcode' =>'41830900', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Manoel Gomes Mendonça, 307 ap2101'],
    ['addressable_id' => 343, 'zipcode' =>'40155030', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jardim Apipema', 'address'=>'R Ranulfo de Oliveira, 537 apt 301 ed.NinaMar'],
    ['addressable_id' => 416, 'zipcode' =>'41810780', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Ten Fernando Tuy, 318/702 -M.Cent Park'],
    ['addressable_id' => 240, 'zipcode' =>'40140810', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Barra', 'address'=>'R Dr João Pondé, 61 apt 603'],
    ['addressable_id' => 92, 'zipcode' =>'41830450', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Rua Ceara, 1233, ap 201'],
    ['addressable_id' => 63, 'zipcode' =>'41830380', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Amazonas, 293 / 701'],
    ['addressable_id' => 256, 'zipcode' =>'41830190', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Santa Catarina, 157 apt 602'],
    ['addressable_id' => 120, 'zipcode' =>'40155050', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jardim Apipema', 'address'=>'R Des Ezequiel Pondé,106 ap.102'],
    ['addressable_id' => 226, 'zipcode' =>'40296730', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Candeal', 'address'=>'R Basilio Catala Castro, 1'],
    ['addressable_id' => 161, 'zipcode' =>'41927430', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Santa Helena, 158 apt 902'],
    ['addressable_id' => 148, 'zipcode' =>'40130020', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Barra Avenida', 'address'=>'R Dra Praguer Froes, 89 apt 302'],
    ['addressable_id' => 184, 'zipcode' =>'42700000', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Lauro de Freitas', 'address'=>'Lot Santo Antônio, s/n qd C lt 51B'],
    ['addressable_id' => 49, 'zipcode' =>'40150130', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Graça', 'address'=>'R Humberto de Campos, 159 / 801'],
    ['addressable_id' => 502, 'zipcode' =>'40080002', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Vitória', 'address'=>'Av 7 de Setembro, 2155'],
    ['addressable_id' => 274, 'zipcode' =>'41810570', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Altino Serbeto de Barros, 345/901'],
    ['addressable_id' => 172, 'zipcode' =>'40150140', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Graça', 'address'=>'R da Paz, 241 apt 101'],
    ['addressable_id' => 491, 'zipcode' =>'41830300', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Emilio Odebrecht, 106  ap 1004 B.A'],
    ['addressable_id' => 449, 'zipcode' =>'40140000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Barra Avenida', 'address'=>'Av Princesa Isabel, 542 apt  801'],
    ['addressable_id' => 361, 'zipcode' =>'40296220', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Candeal', 'address'=>'R Carlos Maron, 252 apt 1202'],
    ['addressable_id' => 13, 'zipcode' =>'40150390', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Graça', 'address'=>'R Martagão Gesteira, 415 apt 401'],
    ['addressable_id' => 401, 'zipcode' =>'41760160', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Costa Azul', 'address'=>'R Cel Durval Mattos, 417ap 501 Ed.CostaVillw'],
    ['addressable_id' => 135, 'zipcode' =>'41150000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Cabula', 'address'=>'R Silveira Martins,CD Pomar, B-267,Ap408'],
    ['addressable_id' => 357, 'zipcode' =>'40170110', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Ondina', 'address'=>'Av Adhemar de Barro, 58 ap 122 The Plaza'],
    ['addressable_id' => 339, 'zipcode' =>'41701020', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Paralela', 'address'=>'Residencial Itaparica, Qd-F2-10-Alphaville-1'],
    ['addressable_id' => 481, 'zipcode' =>'40155810', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jardim Apipema', 'address'=>'R Plinio Moscoso, 1074 Ed VivendaApipena'],
    ['addressable_id' => 445, 'zipcode' =>'49095170', 'state'=>'SE','city'=>'Aracaju ', 'district'=> 'Jabotiana ', 'address'=>'Rua João Leal Soares, 34 Conjunto JK '],
    ['addressable_id' => 4, 'zipcode' =>'42700000', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Vilas do Atlantico', 'address'=>'R Prof Itamaraca, 36 Qd-B-07'],
    ['addressable_id' => 396, 'zipcode' =>'41680050', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Patamares', 'address'=>'R Bicuiba, 1291 ap 1401-B'],
    ['addressable_id' => 200, 'zipcode' =>'40100210', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Garcia', 'address'=>'R Clemente Pereira, 28'],
    ['addressable_id' => 9, 'zipcode' =>'41820700', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Caminho das Árvores', 'address'=>'R Clarival P Valadares, 279 ap 403'],
    ['addressable_id' => 195, 'zipcode' =>'41810710', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Eng Adhemar Fontes, 254 ap 401'],
    ['addressable_id' => 332, 'zipcode' =>'41613015', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jaguaribe', 'address'=>'R da Fauna, 449 CD Veredas Al.Marte 101'],
    ['addressable_id' => 230, 'zipcode' =>'41810820', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Manoel Gomes de Mendonça, 93 apt 502'],
    ['addressable_id' => 453, 'zipcode' =>'41830530', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Territorio do Rio Branco, 317 ap 101'],
    ['addressable_id' => 156, 'zipcode' =>'40080002', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Vitória', 'address'=>'Av Sete de Setembro, 2155 apt 1408'],
    ['addressable_id' => 402, 'zipcode' =>'41820500', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Caminho das Árvores', 'address'=>'Al das Algarobas, 137'],
    ['addressable_id' => 29, 'zipcode' =>'41810110', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Guillard Muniz, 175 ap 201'],
    ['addressable_id' => 87, 'zipcode' =>'41730101', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Paralela', 'address'=>'Av Luis Viana Filho, 490ap1402 ResLeParc T-07'],
    ['addressable_id' => 181, 'zipcode' =>'40155250', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jardim Apipema', 'address'=>'R Sabino Silva, 273 ap 402 Ed. Abilio Peixoto'],
    ['addressable_id' => 383, 'zipcode' =>'41810210', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Guerra Junqueiro, 08'],
    ['addressable_id' => 500, 'zipcode' =>'41185595', 'state'=>'BA','city'=>'Salvador', 'district'=> 'São Gonçalo', 'address'=>'R Vila da Conceição, 12 - E'],
    ['addressable_id' => 287, 'zipcode' =>'41830492', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Altino Serbeto de Barros, 295 ap 1904'],
    ['addressable_id' => 268, 'zipcode' =>'41820660', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Caminho das Árvores', 'address'=>'R Timbó, 675 ap 201'],
    ['addressable_id' => 507, 'zipcode' =>'41940080', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Rio Vermelho', 'address'=>'R Aimorés, 290/ 404 Ed Piazza Margaritta'],
    ['addressable_id' => 150, 'zipcode' =>'41815410', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Manoel Correia Garcia, 27 ap 102'],
    ['addressable_id' => 412, 'zipcode' =>'40450590', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Roma/Mares', 'address'=>'R Galileia, 17'],
    ['addressable_id' => 394, 'zipcode' =>'40150000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Graça', 'address'=>'Av Princesa Leopoldina, 17/19 ap 202'],
    ['addressable_id' => 382, 'zipcode' =>'41810315', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Aristides Fraga Lima,385 ap 502'],
    ['addressable_id' => 69, 'zipcode' =>'41815070', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R João Varela, 259'],
    ['addressable_id' => 106, 'zipcode' =>'40296250', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Candeal', 'address'=>'R Dr Alberto Pondé, 02 Ap 801'],
    ['addressable_id' => 10, 'zipcode' =>'40295030', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Horto Florestal', 'address'=>'R Cons Correa de Menezes, 182 ap 1203'],
    ['addressable_id' => 233, 'zipcode' =>'41600665', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Stella Maris', 'address'=>'R Prof Carlos Ott, 142 cs24 CdStelaVile'],
    ['addressable_id' => 498, 'zipcode' =>'41650010', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã', 'address'=>'Av Orlando Gomes,s/nPq CostaVerde Q-L,LT-07'],
    ['addressable_id' => 398, 'zipcode' =>'40155250', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jardim Apipema', 'address'=>'R Prof Sabino Silva, 282 ap 1001'],
    ['addressable_id' => 407, 'zipcode' =>'41810030', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Alexandre Humboldt, 188'],
    ['addressable_id' => 320, 'zipcode' =>'41701015', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Alphaville 1', 'address'=>'Av Alphaville 451,CdForestVille, T.Fig. Ap403'],
    ['addressable_id' => 346, 'zipcode' =>'41830490', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Al Catânia, 148 / 1101 Ed. Mansão Thessaly'],
    ['addressable_id' => 22, 'zipcode' =>'41600270', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Stella Maris', 'address'=>'Al Praia de Guaratuba, 698 cs 140-VilaFerrara'],
    ['addressable_id' => 133, 'zipcode' =>'41815190', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Jardim Alto do itaigara, 96'],
    ['addressable_id' => 74, 'zipcode' =>'41820370', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Caminho das Árvores', 'address'=>'R do Ébano, 195 ap 201 - Ed PalacePresidente'],
    ['addressable_id' => 455, 'zipcode' =>'41650505', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã', 'address'=>'R dos Passaros Pretos, CD Ver Piatã CS H14'],
    ['addressable_id' => 336, 'zipcode' =>'41815180', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Prof  Zahide Machado Neto, 331'],
    ['addressable_id' => 474, 'zipcode' =>'41815150', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Heitor Macedo Costa, 341 ap 203'],
    ['addressable_id' => 266, 'zipcode' =>'41720025', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Imbuí', 'address'=>'R Alberto Fiuza, 367 ap 1003 CD SummerTime'],
    ['addressable_id' => 140, 'zipcode' =>'41810110', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Guilhard Muniz, 55 ap 902 EdCatarinaParagua'],
    ['addressable_id' => 56, 'zipcode' =>'40140000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Barra', 'address'=>'Av Princesa Isabel, 526 ap 104'],
    ['addressable_id' => 310, 'zipcode' =>'41815270', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Wanderley Pinho 735 apt° 1.101'],
    ['addressable_id' => 231, 'zipcode' =>'48040310', 'state'=>'BA','city'=>'Alagoinhas', 'district'=> 'Juracy Magalhaes', 'address'=>'R Coronel Pedro Dantas, 190/ 204'],
    ['addressable_id' => 15, 'zipcode' =>'41502310', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jardim das Margaridas', 'address'=>'R Acacia Amarela, 1009'],
    ['addressable_id' => 326, 'zipcode' =>'41815340', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Erico Verissimo, 101 ap 501'],
    ['addressable_id' => 415, 'zipcode' =>'41750166', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Armação', 'address'=>'R Rodolpho Coelho Cavalcante, 169/ 2003'],
    ['addressable_id' => 280, 'zipcode' =>'40150000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Graça', 'address'=>'R Oito de Dezembro,254/ 802-EdPedra daGraça'],
    ['addressable_id' => 465, 'zipcode' =>'42700000', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Centro', 'address'=>'Av Luiz Tarquinio Pontes 926 - R Equus cs 67 - Condomínio Vog House Jockey Club '],
    ['addressable_id' => 501, 'zipcode' =>'41815180', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Zahidé Machado Neto, 66'],
    ['addressable_id' => 127, 'zipcode' =>'41650010', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã', 'address'=>'Av Orlando Gomes, 1080'],
    ['addressable_id' => 40, 'zipcode' =>'40080002', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Vitória', 'address'=>'Av Sete de Setembro, 2173/ 602'],
    ['addressable_id' => 84, 'zipcode' =>'41750190', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jardim Armação', 'address'=>'R João Mendes da Costa Filho, 285/ 801'],
    ['addressable_id' => 259, 'zipcode' =>'41820660', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Caminho das Árvores', 'address'=>'R Timbó, 519 - Ed. Residencial São Paulo'],
    ['addressable_id' => 196, 'zipcode' =>'41900000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Amaralina', 'address'=>'R Visc de Itaborahí, 972 / 201 - Ed.Trigo'],
    ['addressable_id' => 463, 'zipcode' =>'40295050', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Horto Florestal', 'address'=>'Av Santa Luzia, 149/ 1801'],
    ['addressable_id' => 134, 'zipcode' =>'48031100', 'state'=>'BA','city'=>'Alagoinhas', 'district'=> 'Jardim Petrolar', 'address'=>'R Holandesa, Qd 23, Lt 07'],
    ['addressable_id' => 58, 'zipcode' =>'40080004', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Vitória', 'address'=>'Av 7 de Setembro, 2090 ap 80T'],
    ['addressable_id' => 427, 'zipcode' =>'41810640', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Arthur Gomes de Carvalho, 615'],
    ['addressable_id' => 68, 'zipcode' =>'40050320', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Nazaré', 'address'=>'R Boulevard America, 695 ap 102'],
    ['addressable_id' => 243, 'zipcode' =>'41830380', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Amazonas, 159/ 304 - Ed. Serra do Nascente'],
    ['addressable_id' => 130, 'zipcode' =>'41900375', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Amaralina', 'address'=>'R Wilson Palmeiras, 95/ 201 Ed. Redentor'],
    ['addressable_id' => 484, 'zipcode' =>'42700000', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Buraquinho', 'address'=>'R Min Antonio Carlos Magalhães, 377-403 B-03'],
    ['addressable_id' => 300, 'zipcode' =>'40100000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Garcia', 'address'=>'Av Leovigildo Filgueiras, 422/ 1604'],
    ['addressable_id' => 117, 'zipcode' =>'40150120', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Graça', 'address'=>'Av Euclydes da Cunha, 475/ 702'],
    ['addressable_id' => 387, 'zipcode' =>'41820680', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Caminho das Árvores', 'address'=>'Al dos Umbuzeiros, 445 ap 1402'],
    ['addressable_id' => 252, 'zipcode' =>'41620340', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itapuã', 'address'=>'R Estrela Dalva, 171'],
    ['addressable_id' => 171, 'zipcode' =>'40150270', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Graça', 'address'=>'R Barão de Loreto, 53'],
    ['addressable_id' => 372, 'zipcode' =>'41613021', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jaguaribe', 'address'=>'Al Netuno, 247'],
    ['addressable_id' => 292, 'zipcode' =>'40296210', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Candeal', 'address'=>'R Leonor Calmon, 74 ap 1201 Ed PrincipeLyon'],
    ['addressable_id' => 464, 'zipcode' =>'42700000', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Itinga', 'address'=>'Rod Est Coco, Km 1,5 -Cd.JddosPássar,Q7 Lt 17'],
    ['addressable_id' => 368, 'zipcode' =>'40279750', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Parque Bela Vista', 'address'=>'R Prof Guiomar Florence, 262/ 101'],
    ['addressable_id' => 244, 'zipcode' =>'42700000', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Portho', 'address'=>'Cond. Pq. Encontro das Aguas, Qd. E Lt. 30'],
    ['addressable_id' => 88, 'zipcode' =>'41830451', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Ceará, 526 ap 1002-A'],
    ['addressable_id' => 187, 'zipcode' =>'41760030', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Costa Azul', 'address'=>'R Vicente Batalha, 57 ap 302'],
    ['addressable_id' => 299, 'zipcode' =>'40140460', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Morro do Gato', 'address'=>'R Guadalajara, 913 ap 201 EdRenato Firpo'],
    ['addressable_id' => 80, 'zipcode' =>'41830520', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Territorio do Guaporé, 377 ap 201'],
    ['addressable_id' => 242, 'zipcode' =>'40150250', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Graça', 'address'=>'R Com Horacio Urpia, 01 ap 902 Ed Solar'],
    ['addressable_id' => 298, 'zipcode' =>'41940340', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Rio Vermelho', 'address'=>'R Barro Vermelho,  221 ap 601'],
    ['addressable_id' => 335, 'zipcode' =>'41830530', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Territorio do Rio Branco, 317 ap 1501'],
    ['addressable_id' => 399, 'zipcode' =>'42700900', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Vilas do Atlântico', 'address'=>'R Praia de Tubarão, s/n Qd-D Lt04 Cd Ecovilas'],
    ['addressable_id' => 499, 'zipcode' =>'42700000', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Pitangueiras', 'address'=>'R Leonardo r da silva, 15'],
    ['addressable_id' => 285, 'zipcode' =>'41830510', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R machado Neto, 267 ap 202 - Ed Vila das Palm'],
    ['addressable_id' => 183, 'zipcode' =>'41810815', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Manoel Andrade, 360 ap 302'],
    ['addressable_id' => 164, 'zipcode' =>'40130030', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Barra Avenida', 'address'=>'Av Princesa Isabel, 669 ap1002 VAugustaTales'],
    ['addressable_id' => 247, 'zipcode' =>'41830490', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Al Catania, 273 ap 1101'],
    ['addressable_id' => 104, 'zipcode' =>'41741572', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituaçu', 'address'=>'R Lima Borges, 225 cs 15'],
    ['addressable_id' => 71, 'zipcode' =>'40157180', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Chame-Chame', 'address'=>'R Des Baldoino Andrade, 211 ap 1802'],
    ['addressable_id' => 419, 'zipcode' =>'40296200', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Candeal', 'address'=>'Al dos Jasmins, 268 Torre-A, ap 1902'],
    ['addressable_id' => 169, 'zipcode' =>'40296200', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Candeal', 'address'=>'Al dos Jasmins, 268 Torre-A, ap 1902'],
    ['addressable_id' => 279, 'zipcode' =>'41603090', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Praia do Flamengo', 'address'=>'R Prof Antonio Augusto Machado, s/n'],
    ['addressable_id' => 211, 'zipcode' =>'41650010', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã', 'address'=>'Av Orlando Gomes, SN CD PqueCostaVerde'],
    ['addressable_id' => 395, 'zipcode' =>'41830440', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Rua Jornalista Joaquim Ferraro Nascimento 102 Ed Bosque da Pituba Apt 1301.'],
    ['addressable_id' => 26, 'zipcode' =>'41810425', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Clara Nunes, 414 ap 1402'],
    ['addressable_id' => 514, 'zipcode' =>'42841000', 'state'=>'BA','city'=>'Camaçari', 'district'=> 'Catu de Abrantes', 'address'=>'Rod BA 099, Km08 CD.Pamplona Lt23'],
    ['addressable_id' => 337, 'zipcode' =>'41815270', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Wanderley Pinho, 305 ap 1202'],
    ['addressable_id' => 263, 'zipcode' =>'41830300', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Emilio Odebrecht, 281 ap 601 B'],
    ['addressable_id' => 350, 'zipcode' =>'41815120', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Mons Eugenio Veiga, 145 ap 701D'],
    ['addressable_id' => 86, 'zipcode' =>'40155210', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jardim Apipema', 'address'=>'R Cristiano otoni, 400 ap 501'],
    ['addressable_id' => 478, 'zipcode' =>'41760150', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Costa Azul', 'address'=>'R Des Manoel Pereira, 98 ap 402'],
    ['addressable_id' => 405, 'zipcode' =>'40150350', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Graça', 'address'=>'R Rio de São Pedro, 205 ap 1601'],
    ['addressable_id' => 235, 'zipcode' =>'40155812', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jardim Apipema', 'address'=>'R Plinio Moscoso, 1275 ap 201'],
    ['addressable_id' => 209, 'zipcode' =>'41830450', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Ceara, 473 ap 502'],
    ['addressable_id' => 376, 'zipcode' =>'41810820', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Manoel Gomes Mendonça, 307 ap 602 (B)'],
    ['addressable_id' => 403, 'zipcode' =>'46760000', 'state'=>'BA','city'=>'Ibicoara', 'district'=> 'Centro', 'address'=>'R Nelson Aguiar, 140'],
    ['addressable_id' => 48, 'zipcode' =>'40130000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Barra', 'address'=>'Av Sete de Setembro, 2901ap 801 N'],
    ['addressable_id' => 188, 'zipcode' =>'40150140', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Graça', 'address'=>'Rua da Paz 301 Ap. 301 Ed. Mansão Fontana di Trevi'],
    ['addressable_id' => 349, 'zipcode' =>'40150140', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Graça', 'address'=>'Rua da Paz 301 ap 301, Ed Mansão Fontana di Trevi'],
    ['addressable_id' => 131, 'zipcode' =>'40296530', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Candeal', 'address'=>'Al dos Anturius, 178 ap 801'],
    ['addressable_id' => 380, 'zipcode' =>'41830270', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Piaui, 269 ap 702'],
    ['addressable_id' => 90, 'zipcode' =>'41940455', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Garibaldi', 'address'=>'R Eduardo José dos Santos, 147 ap 130B'],
    ['addressable_id' => 100, 'zipcode' =>'41613076', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jaguaribe', 'address'=>'Rua Desembargador Lafayette Velloso 1 Condomínio Jardim Gantois, QD D1'],
    ['addressable_id' => 57, 'zipcode' =>'41612060', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jardim Placaford', 'address'=>'Av Princesa Isabel, 22'],
    ['addressable_id' => 352, 'zipcode' =>'41810001', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'Av Paulo VI, 2138 ap 1301'],
    ['addressable_id' => 406, 'zipcode' =>'44571021', 'state'=>'BA','city'=>'Santo Antonio de Jesus', 'district'=> 'Centro', 'address'=>'R Isaias alves, 382'],
    ['addressable_id' => 333, 'zipcode' =>'40150360', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Graça', 'address'=>'R Manoel Barreto, 441 ap 1501'],
    ['addressable_id' => 99, 'zipcode' =>'42833000', 'state'=>'BA','city'=>'Camaçari', 'district'=> 'Barra do Jacuípe', 'address'=>'Est do Coco, Km31CDVilasJacuipe, Etapa2 Qd17'],
    ['addressable_id' => 206, 'zipcode' =>'41830498', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Ten Fernando Tuy, 230 ap 1502'],
    ['addressable_id' => 341, 'zipcode' =>'41830520', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Territorio Gaporé, 317 ap 601'],
    ['addressable_id' => 305, 'zipcode' =>'41750090', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Armação', 'address'=>'R Alfredo Gomes de Oliveira, 84 ap 1202 Ed Mar Sorrento'],
    ['addressable_id' => 288, 'zipcode' =>'40286050', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Brotas', 'address'=>'1ª Travessa Waldemar Falcão do Horto, 759 ap 301'],
    ['addressable_id' => 508, 'zipcode' =>'41830630', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Hilton Rodriigues, 46 ap 904'],
    ['addressable_id' => 411, 'zipcode' =>'41810425', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Clara Nunes, 376 ap 202 torre 1, Loteamento Aquarius'],
    ['addressable_id' => 414, 'zipcode' =>'41650000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã', 'address'=>'Av Otavio Mangabeira, 11881 B-05 ap 207'],
    ['addressable_id' => 138, 'zipcode' =>'41750010', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Armação', 'address'=>'R Melvin Jones, 300 ap 1110'],
    ['addressable_id' => 291, 'zipcode' =>'41613100', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jaguaribe', 'address'=>'R hacckel Jose de Almeida, 139 ap 702-C'],
    ['addressable_id' => 222, 'zipcode' =>'41830630', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Nilton Rodrigues, 233 ap 803'],
    ['addressable_id' => 325, 'zipcode' =>'41940090', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Rio Vermelho', 'address'=>'R Tupinambas, 421 ap 101'],
    ['addressable_id' => 355, 'zipcode' =>'41810620', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Magno Valente, 391 ap 1601'],
    ['addressable_id' => 197, 'zipcode' =>'41613100', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jaguaribe', 'address'=>'R Haeckel Jose de Almeida, 139 ap 702-c'],
    ['addressable_id' => 472, 'zipcode' =>'41810110', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Guillard Muniz, 55 apto 202'],
    ['addressable_id' => 360, 'zipcode' =>'41701035', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Alphaville 1', 'address'=>'R Parati, 134'],
    ['addressable_id' => 436, 'zipcode' =>'42701270', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Pitangueiras', 'address'=>'R Itaju do Colonia, 483 apto 203 Ed Ilha Bela'],
    ['addressable_id' => 54, 'zipcode' =>'40285450', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Brotas', 'address'=>'R Odilon Dórea, 67 ap 402 Ed RichardWagner'],
    ['addressable_id' => 307, 'zipcode' =>'41830380', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Amazonas, 1019 apto 1201 ED Baía Sueste'],
    ['addressable_id' => 204, 'zipcode' =>'41650400', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã', 'address'=>'R Aristóteles da Costa Leal, 08'],
    ['addressable_id' => 168, 'zipcode' =>'40080002', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Vitória', 'address'=>'Av Sete de Setembro, 2125 apto 501'],
    ['addressable_id' => 390, 'zipcode' =>'41750030', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jardim Armação', 'address'=>'R Rodrigues Dorea, 63 Cond Canto da Praia'],
    ['addressable_id' => 124, 'zipcode' =>'41815140', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Delegado Walter Lino Drummond, 69/602'],
    ['addressable_id' => 59, 'zipcode' =>'41680210', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã', 'address'=>'R Juruna, 338 Cond Aldeia Jaguaribe'],
    ['addressable_id' => 296, 'zipcode' =>'41815140', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Delegado Walter Lino Drummond, 69/602'],
    ['addressable_id' => 37, 'zipcode' =>'41820660', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Caminho das Árvores', 'address'=>'R Do Timbó, 630 ap 302 Vila Fenícia'],
    ['addressable_id' => 381, 'zipcode' =>'41815215', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Alto do Itaigara', 'address'=>'R Dr. Hosannah de Oliveira, 156 ao 101'],
    ['addressable_id' => 426, 'zipcode' =>'41680220', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Patamares', 'address'=>'R Juruna, 372 Cond Aldeia Jaguaribe'],
    ['addressable_id' => 359, 'zipcode' =>'41820340', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Caminho das Árvores', 'address'=>'R Benjoim, 47 ap 401 '],
    ['addressable_id' => 475, 'zipcode' =>'41741439', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituaçú', 'address'=>'R Julio Rodrigues, 20 Cond Jd California'],
    ['addressable_id' => 487, 'zipcode' =>'41810600', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Dr. Eduardo Bahiana, 47 ap 1102'],
    ['addressable_id' => 311, 'zipcode' =>'41830451', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Ceará, 606 ap 402 A'],
    ['addressable_id' => 205, 'zipcode' =>'41815150', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Reitor Macedo Costa, 341 ap 701'],
    ['addressable_id' => 446, 'zipcode' =>'41815340', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R  Érico Veríssimo, 291 ap 1504'],
    ['addressable_id' => 85, 'zipcode' =>'41820700', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Caminho das Árvores', 'address'=>'R Clarival do Prado Valadares, 119 ap 102'],
    ['addressable_id' => 118, 'zipcode' =>'41810710', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Eng Ademar Fontes, 158 ap 102'],
    ['addressable_id' => 477, 'zipcode' =>'40170130', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Rio Vermelho', 'address'=>'Av  Garibaldi, 2562 ap 1802'],
    ['addressable_id' => 67, 'zipcode' =>'41701020', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Alphaville 1', 'address'=>'Residencial Itaparica, Lt 10 Qd F2'],
    ['addressable_id' => 420, 'zipcode' =>'40140461', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Barra', 'address'=>'R Guadalajara, 430 ap 1102'],
    ['addressable_id' => 1, 'zipcode' =>'41720000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Imbuí', 'address'=>'R João José Rescala, 62 ap 1203 '],
    ['addressable_id' => 128, 'zipcode' =>'41830490', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Al Catanis, 181 apto 1502'],
    ['addressable_id' => 232, 'zipcode' =>'41815140', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Delegado Walter Lino DrumMOND, 796'],
    ['addressable_id' => 202, 'zipcode' =>'40295010', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Horto Florestal', 'address'=>'R Waldemar Falcão, 1737 ap 601'],
    ['addressable_id' => 323, 'zipcode' =>'42707140', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Vilas do Atlântico', 'address'=>'Al Praia so Sonho, 38 Qd E9'],
    ['addressable_id' => 330, 'zipcode' =>'41815320', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Almeida Garret, 107 ap 901'],
    ['addressable_id' => 21, 'zipcode' =>'41815300', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Afonso Ruy de Souza, 845'],
    ['addressable_id' => 302, 'zipcode' =>'41820370', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Caminho das Árvores', 'address'=>'R DO EBANO, 195 AP 1002'],
    ['addressable_id' => 160, 'zipcode' =>'41650505', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã', 'address'=>'R dos Passaros Pretos, 128'],
    ['addressable_id' => 378, 'zipcode' =>'41603200', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Praia do Flamengo', 'address'=>'Al Mar Del Plata, Cd ResRec Sol, cs 04'],
    ['addressable_id' => 364, 'zipcode' =>'41830260', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Maranhão, 445 ap 1402'],
    ['addressable_id' => 109, 'zipcode' =>'41820020', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Caminho das Árvores', 'address'=>'Av Tancredo Neves, 620 ap 2106 T.Residencial'],
    ['addressable_id' => 432, 'zipcode' =>'41815180', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Prof Zanide Machado Neto, 89'],
    ['addressable_id' => 328, 'zipcode' =>'40170110', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Ondina', 'address'=>'Av Adhemar de Barros, 58 ap 318'],
    ['addressable_id' => 64, 'zipcode' =>'40150360', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Graça', 'address'=>'R Manoel Barreto, 305 ap 302'],
    ['addressable_id' => 147, 'zipcode' =>'41820340', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Caminho das Árvores', 'address'=>'R do Benjoim, 866 ap 902 Ed.RecTropical'],
    ['addressable_id' => 347, 'zipcode' =>'41820021', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Av Tancredo Neves, 2227 ap 2407 - I'],
    ['addressable_id' => 14, 'zipcode' =>'41650320', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã', 'address'=>'Rua Guaraçaina, nº 530'],
    ['addressable_id' => 451, 'zipcode' =>'41620430', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itapuã', 'address'=>'R Passagarda, 866 cs 76'],
    ['addressable_id' => 322, 'zipcode' =>'41820360', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Caminho das Árvores', 'address'=>'R da Graviola, 364 ap 501'],
    ['addressable_id' => 212, 'zipcode' =>'41750030', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Armação', 'address'=>'R Rodrigues Dorea, 230 ap 1102'],
    ['addressable_id' => 448, 'zipcode' =>'41680050', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Patamares', 'address'=>'R Bicuiba, 1454 ap 602 Bl A Ed Maison Biarritz'],
    ['addressable_id' => 265, 'zipcode' =>'41830230', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Messe do Amor, 74 ap 101'],
    ['addressable_id' => 452, 'zipcode' =>'42712740', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Portão', 'address'=>'Av Santos Dumont, 5481 cs A22'],
    ['addressable_id' => 167, 'zipcode' =>'41770395', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Stiep', 'address'=>'R Edistio Pondé, 141 ap 1303'],
    ['addressable_id' => 293, 'zipcode' =>'41650640', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã', 'address'=>'R Pankarare, 79'],
    ['addressable_id' => 409, 'zipcode' =>'41830270', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Piaui, 679'],
    ['addressable_id' => 454, 'zipcode' =>'41815120', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Mons Eugenio Veiga, 145 T.Vita ap 402'],
    ['addressable_id' => 417, 'zipcode' =>'41815215', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Dr. Hosannah de Oliveira,  153 ap 1302'],
    ['addressable_id' => 251, 'zipcode' =>'41830475', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Cicero Simoes, 119 ap 802'],
    ['addressable_id' => 457, 'zipcode' =>'41830510', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Machado Neto, 267 ap 601'],
    ['addressable_id' => 60, 'zipcode' =>'40080002', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Vitória', 'address'=>'Av Sete de Setembro, 1307 ap 1002-B'],
    ['addressable_id' => 126, 'zipcode' =>'41830494', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Prof Leopoldo Amaral, 429'],
    ['addressable_id' => 494, 'zipcode' =>'41760200', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Costa Azul', 'address'=>'R Mons Gaspar Sadoc, 508 ap 1302-A'],
    ['addressable_id' => 431, 'zipcode' =>'40150390', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Graça', 'address'=>'R Martagão Gesteira, 480 ap 1301'],
    ['addressable_id' => 443, 'zipcode' =>'41830450', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Ceara, 265 ap 501-B'],
    ['addressable_id' => 306, 'zipcode' =>'41701020', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Alphaville 1', 'address'=>'R das Araras, 97 Res Itaparica'],
    ['addressable_id' => 281, 'zipcode' =>'41810001', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'Av Paulo VI, 2138 ap 1301'],
    ['addressable_id' => 39, 'zipcode' =>'41810180', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Sotero Monteiro, 207 ap 1201'],
    ['addressable_id' => 495, 'zipcode' =>'42712901', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Portão', 'address'=>'CD Encontro das Aguas, Qd.F LT30'],
    ['addressable_id' => 154, 'zipcode' =>'40155250', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jardim Apipema', 'address'=>'R Prof Sabino Silva, 1077 ap 901'],
    ['addressable_id' => 404, 'zipcode' =>'41815010', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Edith Gama e Abreu, 196 CD Pedra Canoa 3010'],
    ['addressable_id' => 303, 'zipcode' =>'41815260', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Marieta Alves, 248'],
    ['addressable_id' => 483, 'zipcode' =>'40279020', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Brotas', 'address'=>'R Prof Ildefonso de Mesquita, 113 ap 701'],
    ['addressable_id' => 177, 'zipcode' =>'41815215', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Dr. Hosannah Oliveira, 112 ap 804'],
    ['addressable_id' => 418, 'zipcode' =>'42712900', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Portão', 'address'=>'Av Dantos Dumont, 5535 Qd Q Lt 28 C V Bosques'],
    ['addressable_id' => 238, 'zipcode' =>'41600630', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Stella Maris', 'address'=>'R F Qd. L, 42 Cond Pq Stella Maris'],
    ['addressable_id' => 103, 'zipcode' =>'41680090', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Patamares', 'address'=>'Av Luiz Viana Filho, Cond Le Parc ap 802'],
    ['addressable_id' => 108, 'zipcode' =>'41810040', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Das Dálias, 42 ap 502'],
    ['addressable_id' => 101, 'zipcode' =>'14680061', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Patamares', 'address'=>'R Ibipitanga, 120 ap 301 Ed Barra Cd Sal Ville'],
    ['addressable_id' => 151, 'zipcode' =>'41650505', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã', 'address'=>'R Dos Pássaros Pretos, 68 Cond Veredas Piatã'],
    ['addressable_id' => 82, 'zipcode' =>'41611585', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itapoã', 'address'=>'Alameda Jardim Itapoã, 284'],
    ['addressable_id' => 297, 'zipcode' =>'42825901', 'state'=>'BA','city'=>'Camaçari', 'district'=> 'Busca Vida', 'address'=>'Estr Do Coco, Km 8 Cond Busca Vida Gleba 26, Lt 12'],
    ['addressable_id' => 34, 'zipcode' =>'41741572', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Patamares', 'address'=>'R Lima Borges, 225 casa 25'],
    ['addressable_id' => 250, 'zipcode' =>'41820390', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Caminho das Árvores', 'address'=>'R Cipreste 244, Aptº 1502'],
    ['addressable_id' => 258, 'zipcode' =>'41680090', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Patamares', 'address'=>'R Le Champ, 125 A ap 901'],
    ['addressable_id' => 375, 'zipcode' =>'40170010', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Ondina', 'address'=>'Av Oceânica, 2400 ap 402'],
    ['addressable_id' => 497, 'zipcode' =>'41830475', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Cicero Simoes, 119 ap 903'],
    ['addressable_id' => 51, 'zipcode' =>'40050090', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Tororó', 'address'=>'R Futuro do Tororó, 6 casa'],
    ['addressable_id' => 489, 'zipcode' =>'41603470', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Praia do Flamengo', 'address'=>'R Engª Magnólia Teixeira, 742 casa 4'],
    ['addressable_id' => 490, 'zipcode' =>'41815340', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Érica Veríssimo, 125'],
    ['addressable_id' => 490, 'zipcode' =>'41815340', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Érica Veríssimo, 125'],
    ['addressable_id' => 152, 'zipcode' =>'41830070', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Pará, 446 ap 2202'],
    ['addressable_id' => 215, 'zipcode' =>'41830300', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Emílio Odebrecht, 281 ap 1401'],
    ['addressable_id' => 36, 'zipcode' =>'41830451', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Ceara, 320 ap 301'],
    ['addressable_id' => 438, 'zipcode' =>'40296250', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Candeal', 'address'=>'R Dr. Alberto Pondé, 411 ap 701'],
    ['addressable_id' => 210, 'zipcode' =>'41680050', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Patamares', 'address'=>'R Biculba, 1454 ap 1402 B'],
    ['addressable_id' => 506, 'zipcode' =>'40140241', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Barra', 'address'=>'R Marques de Caravelas, 295 ap 1'],
    ['addressable_id' => 139, 'zipcode' =>'44032156', 'state'=>'BA','city'=>'Feira de Santana', 'district'=> 'Campo Limpo', 'address'=>'R D, 172 Morada das Árvores'],
    ['addressable_id' => 444, 'zipcode' =>'41830450', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Ceará, 265ap 1304 Cd San Diego'],
    ['addressable_id' => 260, 'zipcode' =>'41770110', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Stiep', 'address'=>'R Purus, 87'],
    ['addressable_id' => 201, 'zipcode' =>'41650010', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã', 'address'=>'Av Orlando Gomes, 806 cs 32 Cd.V.Piatã'],
    ['addressable_id' => 237, 'zipcode' =>'42820920', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Caminho de Areia', 'address'=>'Av. Caminho de Areia nº 160, Conjunto JK , bloco 32'],
    ['addressable_id' => 255, 'zipcode' =>'41600665', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Stella Maris', 'address'=>'R Prof Carlos Ott, 142 Cd.Stella Ville cs 07'],
    ['addressable_id' => 319, 'zipcode' =>'40270900', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Vila Laura', 'address'=>'Rua Raul Leite, 1470, Cond. Villa Privilege - Torre 1, apto 2906'],
    ['addressable_id' => 289, 'zipcode' =>'40270240', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Vila Laura', 'address'=>'Rua Dr. Genésio Sales, 226 - Ed Laura Costa Ap 801'],
    ['addressable_id' => 218, 'zipcode' =>'41750000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Jardim Armação', 'address'=>'Rua General Braulio Guimarães, 71 ap 201'],
    ['addressable_id' => 159, 'zipcode' =>'41820620', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Rua Magno Valente, 391, apt 1101'],
    ['addressable_id' => 38, 'zipcode' =>'41815090', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'Rua Oswaldo Valente, 602, ap 502'],
    ['addressable_id' => 132, 'zipcode' =>'41680048', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Patamares', 'address'=>'Rua Mangalô, 233, ap 101'],
    ['addressable_id' => 459, 'zipcode' =>'41180710', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Saboeiro', 'address'=>'Rua Beco da Coruja, 271, casa 15'],
    ['addressable_id' => 52, 'zipcode' =>'41701015', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Alphaville 1', 'address'=>'Av. Alphaville, 824 apt 104, edf. Prime Ville'],
    ['addressable_id' => 460, 'zipcode' =>'41830465', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Alameda verona, 112, Ed Cedro Residencial, ap 502'],
    ['addressable_id' => 47, 'zipcode' =>'41820000', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Av. Paulo VI, nº 2099, apt 1103, Edf Modernus'],
    ['addressable_id' => 413, 'zipcode' =>'40157190', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Chame-Chame', 'address'=>'Rua Plínio Moscoso, 166/401'],
    ['addressable_id' => 273, 'zipcode' =>'41815300', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R AFONSO RUY DE SOUZA, 777'],
    ['addressable_id' => 374, 'zipcode' =>'41740090', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituaçu', 'address'=>'Av. Pinto de Aguiar, 306, rua F, casa 58'],
    ['addressable_id' => 439, 'zipcode' =>'41760120', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Costa Azul', 'address'=>'R Prof Isaias Alves de Almeida, 266 ap 32-B'],
    ['addressable_id' => 315, 'zipcode' =>'41830451', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Ceará, 356 ap 602 - Ed Royal Garden apto 602'],
    ['addressable_id' => 344, 'zipcode' =>'41830630', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Rua Hilton Rodrigues, 122, apt 402B'],
    ['addressable_id' => 400, 'zipcode' =>'41830315', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Renato de Menezes Berenguer, 185 ap 804 B'],
    ['addressable_id' => 505, 'zipcode' =>'41815120', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'R Mons Eugenio Veiga, 173 ap 1004'],
    ['addressable_id' => 91, 'zipcode' =>'41810825', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Alberto Valença, 166 aptº 903 Edf. Mansão Emília Segura'],
    ['addressable_id' => 277, 'zipcode' =>'41820700', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Caminho das Árvores', 'address'=>'R Clarival Prado Valadares, 279/ 1401'],
    ['addressable_id' => 234, 'zipcode' =>'40081305', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Vitória', 'address'=>'Largo da Vitória, nº 2 - Edf. Sanremo apt 401'],
    ['addressable_id' => 173, 'zipcode' =>'41815130', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Itaigara', 'address'=>'Rua Dr. Antonio Monteiro, n 105, apt 1102'],
    ['addressable_id' => 365, 'zipcode' =>'42711610', 'state'=>'BA','city'=>'Lauro de Freitas', 'district'=> 'Caji', 'address'=>'Segunda Travessa Dr. Gerino de Souza Filho, 158'],
    ['addressable_id' => 55, 'zipcode' =>'41830492', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Altino Serbeto Barros, 295/ 302  Ed Maisson Montparnasse'],
    ['addressable_id' => 203, 'zipcode' =>'41830530', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'R Território do Rio Branco, 84 aptº 802'],
    ['addressable_id' => 227, 'zipcode' =>'41810001', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Pituba', 'address'=>'Av. Paulo VI, nº 2099, apt 1103, Edf Modernus'],
    ['addressable_id' => 270, 'zipcode' =>'41613100', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã', 'address'=>'R Haeckel José Almeida-Cd.Jd Piatã, Qd 3 Lt 12'],
    ['addressable_id' => 329, 'zipcode' =>'41650400', 'state'=>'BA','city'=>'Salvador', 'district'=> 'Piatã', 'address'=>'Rua Aristoteles da Costa Leal, 140 Cond. Risedencial Piatã casa 44'],
    
    
];

?>

