<?php 

$emails = [

				
	['emailable_id' => 189, 'email' =>'hbohumberto@petrobras.com.br'],	['emailable_id' => 189, 'email' =>'htresm@yahoo.com.br'],	
	['emailable_id' => 447, 'email' =>'ramires@petrobras.com.br'],		
	['emailable_id' => 7, 'email' =>'adrianaseixas@petrobras.com.br'],		
	['emailable_id' => 456, 'email' =>'ronaldov@petrobras.com.br'],		
	['emailable_id' => 331, 'email' =>'teka.apuka@gmail.com'],		
	['emailable_id' => 225, 'email' =>'jpneto@petrobras.com.br'],	['emailable_id' => 225, 'email' =>'joaopereira59@gmail.com'],	
	['emailable_id' => 441, 'email' =>'abude@petrobras.com.br'],		
	['emailable_id' => 186, 'email' =>'napoli@petrobras.com.br'],		
	['emailable_id' => 129, 'email' =>'eliedno@petrobras.com.br'],		
	['emailable_id' => 248, 'email' =>'gilamp@petrobras.com.br'],	['emailable_id' => 248, 'email' =>'gilamp@uol.com.br'],	
	['emailable_id' => 62, 'email' =>'paulomendes@petrobras.com.br'],		
	['emailable_id' => 393, 'email' =>'milhomem@petrobras.com.br                      '],	['emailable_id' => 393, 'email' =>'milhomem@petrobras.com.br'],	
	['emailable_id' => 142, 'email' =>'ezaulbarros@gmail.com'],		
	['emailable_id' => 290, 'email' =>'lucienedublin@petrobras.com.br'],		
	['emailable_id' => 220, 'email' =>'giron@petrobras.com.br'],		
	['emailable_id' => 315, 'email' =>'marba@petrobras.com.br'],		
	['emailable_id' => 73, 'email' =>'caioagra@petrobras.com.br'],		
	['emailable_id' => 165, 'email' =>'gauthier.abreu@gmail.com'],		
	['emailable_id' => 340, 'email' =>'molivia@petrobras.com.br'],		
	['emailable_id' => 304, 'email' =>'leaf@petrobras.com.br'],		
	['emailable_id' => 143, 'email' =>'fabiorosa@petrobras.com.br'],		
	['emailable_id' => 294, 'email' =>'lfcalves@petrobras.com.br'],		
	['emailable_id' => 213, 'email' =>'jaof@petrobras.com.br'],		
	['emailable_id' => 469, 'email' =>'sandro.h@petrobras.com.br'],		
	['emailable_id' => 392, 'email' =>'pcesars@petrobras.com.br'],		
	['emailable_id' => 89, 'email' =>'carmocovas@petrobras.com.br'],		
	['emailable_id' => 371, 'email' =>'napofers@petrobras.com.br'],		
	['emailable_id' => 278, 'email' =>'lmsantos@petrobras.com.br'],		
	['emailable_id' => 180, 'email' =>'gui.gs@petrobras.com.br'],	['emailable_id' => 180, 'email' =>'gui.a458@gmail.com'],	
			
	['emailable_id' => 11, 'email' =>'airtonjose@petrobras.com.br'],		
	['emailable_id' => 512, 'email' =>'wilde@petrobras.com.br'],		
	['emailable_id' => 253, 'email' =>'luis.raposo@petrobras.com.br'],		
	['emailable_id' => 24, 'email' =>'alexgomes@petrobras.com.br'],	['emailable_id' => 24, 'email' =>'lucas321@terra.com.br'],	
	['emailable_id' => 257, 'email' =>'joseserrao@petrobras.com.br'],	['emailable_id' => 257, 'email' =>'joseserrao@gmail.com'],	
	['emailable_id' => 434, 'email' =>'ricardosantanna@petrobras.com.br'],	['emailable_id' => 434, 'email' =>'santannasan63@gmail.com'],	['emailable_id' => 434, 'email' =>'santannasan@uol.com.br'],
	['emailable_id' => 93, 'email' =>'cesarpf@petrobras.com.br'],		
	['emailable_id' => 338, 'email' =>'msocorro@petrobras.com.br'],		
	['emailable_id' => 442, 'email' =>'roberto.ramos@petrobras.com.br'],	['emailable_id' => 442, 'email' =>'rcrs65@gmail.com'],	
	['emailable_id' => 46, 'email' =>'angeloeng@bol.com.br'],		
	['emailable_id' => 113, 'email' =>'davisilva@petrobras.com.br'],		
	['emailable_id' => 424, 'email' =>'renatonerypinto@hotmail.com'],		
	['emailable_id' => 16, 'email' =>'acn@petrobras.com.br'],		
	['emailable_id' => 179, 'email' =>'guigov@petrobras.com.br'],		
	['emailable_id' => 107, 'email' =>'crisrichard@petrobras.com.br'],	['emailable_id' => 107, 'email' =>'cristeixeira2@hotmail.com'],	
	['emailable_id' => 107, 'email' =>'crisrichard@petrobras.com.br'],		
	['emailable_id' => 270, 'email' =>'juvenalmota@petrobras.com.br'],		
	['emailable_id' => 471, 'email' =>'selmassaca@gmail.com'],		
	['emailable_id' => 219, 'email' =>'joao.neto@petrobras.com.br'],		
	['emailable_id' => 53, 'email' =>'acs.paz@hotmail.com'],		
	['emailable_id' => 384, 'email' =>'ofreitas@petrobras.com.br'],		
	['emailable_id' => 23, 'email' =>'alexbraga@petrobras.com.br'],		
	['emailable_id' => 509, 'email' =>'wpr2012@hotmail.com'],		
	['emailable_id' => 261, 'email' =>'jrleite@petrobras.com.br'],		
	['emailable_id' => 158, 'email' =>'fpmarques@petrobras.com.br'],		
	['emailable_id' => 227, 'email' =>'joalex@petrobras.com.br'],		
	['emailable_id' => 356, 'email' =>'mpiraja@petrobras.com.br'],		
	['emailable_id' => 25, 'email' =>'alexmm@petrobras.com.br'],		
	['emailable_id' => 473, 'email' =>'postigo@petrobras.com.br'],		
	['emailable_id' => 312, 'email' =>'manoelpimentel@petrobras.com.br'],	['emailable_id' => 312, 'email' =>'manoelpimentel@ig.com.br'],	
	['emailable_id' => 102, 'email' =>'clerival@GMAIL.COM'],		
	['emailable_id' => 170, 'email' =>'geruzam@terra.com.br'],		
	['emailable_id' => 199, 'email' =>'jacirarcarvalho@yahoo.com.br'],		
	['emailable_id' => 254, 'email' =>'luiz_dutra@hotmail.com.br'],		
	['emailable_id' => 198, 'email' =>'saraivaum@yahoo.com.br'],		
	['emailable_id' => 166, 'email' =>'gedsonmeira@petrobras.com.br'],	['emailable_id' => 166, 'email' =>'gedsonmeira@hotmail.com'],	
	['emailable_id' => 385, 'email' =>'orlandoponde@gmail.com'],	['emailable_id' => 385, 'email' =>'orlandoponde@petrobras.com.br'],	
	['emailable_id' => 353, 'email' =>'mauponde@yahoo.com.br'],		
	['emailable_id' => 176, 'email' =>'glaudmar@petrobras.com.br'],		
	['emailable_id' => 8, 'email' =>'adriano.muricy@petrobras.com.br'],	['emailable_id' => 8, 'email' =>'adr.muricy@gmail.com'],	
	['emailable_id' => 504, 'email' =>'veridiano74@gmail.com'],		
	['emailable_id' => 327, 'email' =>'marcosandre.mar@gmail.com'],	['emailable_id' => 327, 'email' =>'marcosandrept@yahoo.com.br'],	
	['emailable_id' => 389, 'email' =>'patricia_castro@petrobras.com.br'],		
	['emailable_id' => 83, 'email' =>'eugenio0004@gmail.com'],		
	['emailable_id' => 42, 'email' =>'andre32@terra.com.br'],		
	['emailable_id' => 437, 'email' =>'ricpperes@gmail.com'],		
	['emailable_id' => 314, 'email' =>'barretofilho@petrobras.com.br'],		
	['emailable_id' => 3, 'email' =>'adelmopsouza@gmail.com'],		
	['emailable_id' => 76, 'email' =>'andre.chastinet@gmail.com'],		
			
	['emailable_id' => 175, 'email' =>'glauber@petrobras.com.br'],		
	['emailable_id' => 155, 'email' =>'cs29@yahoo.com.br'],		
	['emailable_id' => 141, 'email' =>'emm@petrobras.com.br'],		
	['emailable_id' => 149, 'email' =>'lopesfernandesbr@gmail.com'],		
	['emailable_id' => 510, 'email' =>'WANDERLEYJR@PETROBRAS.COM.BR'],		
	['emailable_id' => 174, 'email' =>'gilsonsiqueira27@gmail.com'],		
	['emailable_id' => 185, 'email' =>'hhsampaio@bol.com.br'],		
	['emailable_id' => 239, 'email' =>'j.aureliano@yahoo.com.br'],		
	['emailable_id' => 365, 'email' =>'miqueias@petrobras.com.br'],		
	['emailable_id' => 116, 'email' =>'delmosantana@hotmail.com'],		
	['emailable_id' => 79, 'email' =>'cbarretto@petrobras.com.br'],		
	['emailable_id' => 2, 'email' =>'alsouza@petrobras.com.br'],		
	['emailable_id' => 275, 'email' =>'leilalopes62@gmail.com'],		
	['emailable_id' => 81, 'email' =>'carlos.leahy.guerra@gmail.com'],		
	['emailable_id' => 324, 'email' =>'marcobz@gmail.com'],		
	['emailable_id' => 496, 'email' =>'toru@petrobras.com.br'],		
	['emailable_id' => 30, 'email' =>'anmachado@petrobras.com.br'],		
	['emailable_id' => 301, 'email' =>'luizamamorim@hotmail.com'],		
	['emailable_id' => 208, 'email' =>'jerfaero@yahoo.com.br'],	['emailable_id' => 208, 'email' =>'jerfson@petrobras.com.br'],	
	['emailable_id' => 137, 'email' =>'egrisi@gmail.com'],		
	['emailable_id' => 264, 'email' =>'joseliceoliveira@gmail.com'],		
	['emailable_id' => 284, 'email' =>'lucianoasc@petrobras.com.br'],		
			
	['emailable_id' => 72, 'email' =>'brunojlima@hotmail.com'],		
	['emailable_id' => 163, 'email' =>'fbaumert@gmail.com'],		
	['emailable_id' => 178, 'email' =>'grazieno.pellegrino@petrobras.com.br '],		
	['emailable_id' => 342, 'email' =>'marifernandesgeofis@gmail.com'],		
	['emailable_id' => 363, 'email' =>'pcjsantos@gmail.com'],		
	['emailable_id' => 391, 'email' =>'pcjsantos@gmail.com'],	['emailable_id' => 391, 'email' =>'pcjsantos@gmail.com'],	
	['emailable_id' => 467, 'email' =>'binamota@gmail.com'],	['emailable_id' => 467, 'email' =>'binamota@gmail.com'],	
	['emailable_id' => 123, 'email' =>'bircho@gmail.com'],		
	['emailable_id' => 217, 'email' =>'jbulhoes@gmail.com'],		
	['emailable_id' => 358, 'email' =>'menandrors@gmail.com'],		
	['emailable_id' => 369, 'email' =>'moniquecsantos@yahoo.com.br'],		
	['emailable_id' => 377, 'email' =>'neylorbahia@gmail.com'],		
	['emailable_id' => 388, 'email' =>'patricia.clarice@gmail.com'],		
	['emailable_id' => 433, 'email' =>'rafalcao@gmail.com'],		
	['emailable_id' => 435, 'email' =>'ricardojesus@petrobras.com.br'],		
	['emailable_id' => 18, 'email' =>'alebrasileiro@gmail.com'],		
	['emailable_id' => 31, 'email' =>'amadamuller@gmail.com'],		
	['emailable_id' => 66, 'email' =>'ariane.politano@gmail.com'],		
	['emailable_id' => 192, 'email' =>'igor.giuliani@gmail.com'],		
	['emailable_id' => 193, 'email' =>'inacioszabo@gmail.com'],		
	['emailable_id' => 214, 'email' =>'joaobsfilho@gmail.com'],		
	['emailable_id' => 282, 'email' =>'lucianaleite2@yahoo.com.br'],		
	['emailable_id' => 309, 'email' =>'maiana@petrobras.com.br'],	['emailable_id' => 309, 'email' =>'maianalopes@gmail.com'],	
	['emailable_id' => 410, 'email' =>'rafael3r@gmail.com'],		
	['emailable_id' => 65, 'email' =>'candurafll@yahoo.com.br'],		
	['emailable_id' => 70, 'email' =>'barbaraquadrosdias@yahoo.com.br'],		
	['emailable_id' => 97, 'email' =>'cintialnleite@bol.com.br'],		
	['emailable_id' => 162, 'email' =>'flsfranco@msn.com'],		
	['emailable_id' => 241, 'email' =>'santosmcj@ig.com.br'],		
	['emailable_id' => 276, 'email' =>'leosuprir@hotmail.com'],		
	['emailable_id' => 386, 'email' =>'oscar.netto@outlook.com'],		
	['emailable_id' => 423, 'email' =>'renatham_@hotmail.com'],	['emailable_id' => 423, 'email' =>'renatha@petrobras.com.br'],	
	['emailable_id' => 19, 'email' =>'alessandrotutu@hotmail.com'],		
	['emailable_id' => 27, 'email' =>'magnameto@bol.com.br'],		
	['emailable_id' => 98, 'email' =>'claborda@petrobras.com.br'],		
	['emailable_id' => 110, 'email' =>'daniel-vict@hotmail.com'],		
	['emailable_id' => 354, 'email' =>'mauriciosguima@gmail.com'],		
	['emailable_id' => 493, 'email' =>'thiago.pains@gmail.com'],		
	['emailable_id' => 286, 'email' =>'lucianosantos27@gmail.com'],	['emailable_id' => 286, 'email' =>'lucianosantos@petrobras.com.br'],	
	['emailable_id' => 136, 'email' =>'ericafreitas@petrobras.com.br'],		
	['emailable_id' => 450, 'email' =>'rodrigo.bastos@petrobras.com.br'],		
	['emailable_id' => 373, 'email' =>'nelson.cruz@petrobras.com.br'],		
	['emailable_id' => 17, 'email' =>'lelesagavienas@gmail.com'],		
	['emailable_id' => 470, 'email' =>'rorizselma@gmail.com'],		
	['emailable_id' => 125, 'email' =>'medeiroses@hotmail.com '],		
	['emailable_id' => 221, 'email' =>'jmariosmed@uol.com.br'],		
	['emailable_id' => 145, 'email' =>'fatimasena@petrobras.com.br'],		
			
	['emailable_id' => 421, 'email' =>'renanqueiros@gmail.com'],		
	['emailable_id' => 408, 'email' =>'priscilla.doria@petrobras.com.br'],		
	['emailable_id' => 262, 'email' =>'bob@petrobras.com.br'],	['emailable_id' => 262, 'email' =>'billboby@hotmail.com'],	
	['emailable_id' => 313, 'email' =>'manucavalcantealmeida@gmail.com'],	['emailable_id' => 313, 'email' =>'manoelaalmeida@petrobras.com.br'],	['emailable_id' => 313, 'email' =>'manoelasi2020@gmail.com'],
	['emailable_id' => 458, 'email' =>'rcleide@petrobras.com.br'],		
	['emailable_id' => 32, 'email' =>'amandagreyce@hotmail.com'],		
	['emailable_id' => 43, 'email' =>'andreamartins419@gmail.com'],	['emailable_id' => 43, 'email' =>'andreahasselmann@petrobras.com.br'],	
	['emailable_id' => 45, 'email' =>'anelore.schetinger@gmail.com'],	['emailable_id' => 45, 'email' =>'anelore@petrobras.com.br'],	
	['emailable_id' => 75, 'email' =>'carlaisa.souza@hotmail.com'],	['emailable_id' => 75, 'email' =>'carlaisa@petrobras.com.br'],	
	['emailable_id' => 96, 'email' =>'cintiapaz@gmail.com'],		
	['emailable_id' => 112, 'email' =>'daniela.leal@petrobras.com.br'],		
	['emailable_id' => 114, 'email' =>'debora.vcm@hotmail.com'],		
			
	['emailable_id' => 146, 'email' =>'fnandaby@gmail.com'],		
	['emailable_id' => 190, 'email' =>'iarinhamamy@hotmail.com '],		
	['emailable_id' => 191, 'email' =>'icaro_cerqueira@hotmail.com'],	['emailable_id' => 191, 'email' =>'icarocrs1804@gmail.com'],	
	['emailable_id' => 194, 'email' =>'ionaab@yahoo.com.br'],		
	['emailable_id' => 207, 'email' =>'jaquelealfisio@hotmail.com'],	['emailable_id' => 207, 'email' =>'jaquelineleal@petrobras.com.br'],	
	['emailable_id' => 267, 'email' =>'Juburity@hotmail.com'],		
	['emailable_id' => 283, 'email' =>'luciana.mmaraujo@gmail.com'],		
	['emailable_id' => 317, 'email' =>'marcelsqueiroz@hotmail.com'],		
	['emailable_id' => 318, 'email' =>'msbarreto@petrobras.com.br'],	['emailable_id' => 318, 'email' =>'marcelosb22@hotmail.com'],	
	['emailable_id' => 348, 'email' =>'marlon.ssantana77@gmail.com'],	['emailable_id' => 348, 'email' =>'marlonsantana@petrobras.com.br'],	
	['emailable_id' => 351, 'email' =>'matheussa@yahoo.com'],	['emailable_id' => 351, 'email' =>'matheussa@petrobras.com.br'],	
	['emailable_id' => 362, 'email' =>'milasampaio@petrobras.com.br'],	['emailable_id' => 362, 'email' =>'miladeo1@ig.com.br'],	
	['emailable_id' => 422, 'email' =>'rcatarinas@hotmail.com'],	['emailable_id' => 422, 'email' =>'renata.dias@petrobras.com.br'],	
	['emailable_id' => 440, 'email' =>'rr_santoo@hotmail.com'],	['emailable_id' => 440, 'email' =>'robertapereira@petrobras.com.br'],	
	['emailable_id' => 428, 'email' =>'renedgfreire@gmail.com'],	['emailable_id' => 428, 'email' =>'rene.freire@petrobras.com.br'],	
	['emailable_id' => 462, 'email' =>'rosevbento@hotmail.com'],	['emailable_id' => 462, 'email' =>'rosebento@petrobras.com.br'],	
['emailable_id' => 480, 'email' =>'silvioguima@hotmail.com'],	['emailable_id' => 480, 'email' =>'silviasrosa@gmail.com'],		
	['emailable_id' => 488, 'email' =>'tatianesferreira@petrobras.com.br'],	['emailable_id' => 488, 'email' =>'tatvba@hotmail.com'],	
	['emailable_id' => 122, 'email' =>'edssonalmeida@uol.com.br'],		
	['emailable_id' => 44, 'email' =>'am_ballet@hotmail.com'],	['emailable_id' => 44, 'email' =>'a_martins@petrobras.com.br'],	
	['emailable_id' => 249, 'email' =>'haroldomcorreia@gmail.com'],		
	['emailable_id' => 334, 'email' =>'mariacarlapalma@gmail.com'],		
			
	['emailable_id' => 397, 'email' =>'paulojbe@gmail.com'],		
	['emailable_id' => 33, 'email' =>'abarb888@gmail.com'],	['emailable_id' => 33, 'email' =>'anabarbara@petrobras.com.br'],	
	['emailable_id' => 78, 'email' =>'caugustofo@gmail.com'],		
	['emailable_id' => 272, 'email' =>'karinecosta@petrobras.com.br'],	['emailable_id' => 272, 'email' =>'karycosta@gmail.com'],	
	['emailable_id' => 429, 'email' =>'nildogoesvg@hotmail.com'],		
	['emailable_id' => 153, 'email' =>'francinidades@gmail.com'],		
	['emailable_id' => 41, 'email' =>'andrecmr@yahoo.com'],		
			
	['emailable_id' => 513, 'email' =>'cedraz.cantabil@gmail.com'],		
	['emailable_id' => 111, 'email' =>'gomesandrade@hotmail.com'],		
	['emailable_id' => 94, 'email' =>'chmagalhaes@hotmail.com'],	['emailable_id' => 94, 'email' =>'chmagalhaessales@gmail.com'],	
	['emailable_id' => 28, 'email' =>'alissonpina@hotmail.com'],		
	['emailable_id' => 119, 'email' =>'dyminbatista@yahoo.com.br'],		
	['emailable_id' => 269, 'email' =>'aneane_23@hotmail.com'],	['emailable_id' => 269, 'email' =>'jusciane@petrobras.com.br'],	
	['emailable_id' => 229, 'email' =>'jlss27@gmail.com'],	['emailable_id' => 229, 'email' =>'jlsantana@petrobras.com.br'],	
	['emailable_id' => 12, 'email' =>'alancq@gmail.com'],		
	['emailable_id' => 461, 'email' =>'rosemberg@gmail.com'],		
	['emailable_id' => 224, 'email' =>'jprochabr@gmail.com'],		
	['emailable_id' => 35, 'email' =>'claudhia@hotmail.com'],	['emailable_id' => 35, 'email' =>'anaclaudiaramos@petrobras.com.br'],	
			
['emailable_id' => 50, 'email' =>'acponde@gmail.com'],			
			
			
			
			
['emailable_id' => 157, 'email' =>'franciscocelsoba@gmail.com'],			
['emailable_id' => 77, 'email' =>'carlosulmsilva@bol.com.br'],	['emailable_id' => 77, 'email' =>'carlosulm2@gmail.com'],		
['emailable_id' => 95, 'email' =>'ciceropp@uol.com.br'],			
['emailable_id' => 345, 'email' =>'mariliakbarreiros@gmail.com'],			
			
			
			
['emailable_id' => 482, 'email' =>'simon2855@gmail.com'],			
['emailable_id' => 486, 'email' =>'ttsilva@terra.com.br'],			
			
['emailable_id' => 216, 'email' =>'borgesmarques@terra.com.br'],			
['emailable_id' => 430, 'email' =>'rbarretos@uol.com.br'],			
['emailable_id' => 223, 'email' =>'carecaene67@gmail.com'],			
			
['emailable_id' => 6, 'email' =>'apandion@uol.com.br'],			
			
			
			
			
['emailable_id' => 182, 'email' =>'schaerhp@gmail.com'],			
			
			
			
			
			
['emailable_id' => 416, 'email' =>'rai.ornellas@terra.com.br'],			
['emailable_id' => 240, 'email' =>'tor.vic@uol.com.br'],			
			
			
			
['emailable_id' => 120, 'email' =>'dilsonfcunha2@hotmail.com'],			
			
			
			
			
['emailable_id' => 49, 'email' =>'antonioareas@gmail.com'],			
['emailable_id' => 502, 'email' =>'vascodosanjos2000@yahoo.com.br'],			
['emailable_id' => 274, 'email' =>'jansenprof@yahoo.com.br'],			
			
['emailable_id' => 491, 'email' =>'tekatravassos@hotmail.com'],			
['emailable_id' => 449, 'email' =>'rodolfomarcal@gmail.com'],			
['emailable_id' => 361, 'email' =>'verasmiguel@terra.com.br'],			
['emailable_id' => 13, 'email' =>'abfilardi@uol.com.br'],			
['emailable_id' => 401, 'email' =>'paulorobertocampos@gmail.com'],			
['emailable_id' => 135, 'email' =>'pami@superig.com.br'],	['emailable_id' => 135, 'email' =>'pamimendes@bol.com.br'],		
['emailable_id' => 357, 'email' =>'meigllem@hotmail.com'],			
['emailable_id' => 339, 'email' =>'mariafatimasequeira@hotmail.com'],			
			
['emailable_id' => 445, 'email' =>'rgwenzinger@gmail.com'],			
['emailable_id' => 4, 'email' =>'adeomires.passos@gmail.com'],			
			
['emailable_id' => 200, 'email' =>'jacobitencourt@yahoo.com.br'],			
['emailable_id' => 9, 'email' =>'camoes.am@gmail.com'],			
['emailable_id' => 195, 'email' =>'iqf@oi.com.br'],			
['emailable_id' => 332, 'email' =>'mariaangela@gmail.com'],			
['emailable_id' => 230, 'email' =>'jljximenes@gmail.com'],			
['emailable_id' => 453, 'email' =>'rbmzzz@uol.com.br'],			
['emailable_id' => 156, 'email' =>'raminelli21@yahoo.com.br'],			
			
['emailable_id' => 29, 'email' =>'almerinda@foccomix.com.br'],			
['emailable_id' => 87, 'email' =>'carlessari@gmail.com'],			
			
['emailable_id' => 383, 'email' =>'oliviosilva@globo.com'],			
['emailable_id' => 500, 'email' =>'magnata.tst@yahoo.com.br'],			
['emailable_id' => 287, 'email' =>'lucianojramos@hotmail.com'],			
['emailable_id' => 268, 'email' =>'juliopontes@terra.com.br'],			
['emailable_id' => 507, 'email' =>'walkerfarias@yahoo.com.br'],			
['emailable_id' => 150, 'email' =>'flaviofontes@uol.com.br'],			
['emailable_id' => 412, 'email' =>'raimundocp0801@gmail.com'],			
['emailable_id' => 394, 'email' =>'ptarsomoreira@yahoo.com.br'],			
['emailable_id' => 382, 'email' =>'odairgs@gmail.com'],			
['emailable_id' => 69, 'email' =>'aurinoaragao@uol.com.br'],			
['emailable_id' => 106, 'email' =>'clorismss@gmail.com'],			
['emailable_id' => 10, 'email' =>'uega.silveira@gmail.com'],			
['emailable_id' => 233, 'email' =>'jorgemuquira@yahoo.com.br'],			
['emailable_id' => 498, 'email' =>'valdireu1@gmail.com'],			
['emailable_id' => 398, 'email' =>'pauloaccioly@hotmail.com'],			
['emailable_id' => 407, 'email' =>'pjbourscheid@gmail.com'],			
['emailable_id' => 320, 'email' =>'msspedroso@gmail.com'],			
['emailable_id' => 346, 'email' =>'mario_sampaio@uol.com.br'],			
['emailable_id' => 22, 'email' =>'alexandrebritocunha@yahoo.com.br'],			
['emailable_id' => 133, 'email' =>'eluzairib@bol.com.br'],			
['emailable_id' => 74, 'email' =>'calucio4@hotmail.com'],			
['emailable_id' => 455, 'email' =>'ronaldopazz@hotmail.com'],			
['emailable_id' => 336, 'email' =>'mariaclaudiadps@hotmail.com'],			
['emailable_id' => 474, 'email' =>'sgpadilha@gmail.com'],			
['emailable_id' => 266, 'email' =>'judevan62@gmail.com'],			
['emailable_id' => 140, 'email' =>'evandroesantos@hotmail.com'],			
['emailable_id' => 56, 'email' =>'acbjesus@hotmail.com'],			
['emailable_id' => 310, 'email' =>'mef.holanda@gmail.com'],			
['emailable_id' => 231, 'email' =>'orge39@hotmail.com'],			
['emailable_id' => 15, 'email' =>'albervan@terra.com.br'],			
['emailable_id' => 326, 'email' =>'mtcf57@gmail.com'],			
['emailable_id' => 415, 'email' =>'nonatobr@uol.com.br'],			
['emailable_id' => 280, 'email' =>'tolentinolucia@ig.com.br'],			
['emailable_id' => 465, 'email' =>'rubao2008@hotmail.com'],			
['emailable_id' => 501, 'email' =>'valtercruz@gmail.com'],			
['emailable_id' => 127, 'email' =>'edjdem@gmail.com'],			
['emailable_id' => 40, 'email' =>'aarosa@bol.com.br'],			
['emailable_id' => 84, 'email' =>'carlos.ag@terra.com.br'],			
['emailable_id' => 259, 'email' =>'jmbmario@hotmail.com'],			
['emailable_id' => 196, 'email' =>'bahiacomh2004@yahoo.com.br'],			
			
['emailable_id' => 134, 'email' =>'enilsonsuzart@yahoo.com.br'],			
['emailable_id' => 58, 'email' =>'linharesdacunha@gmail.com'],			
['emailable_id' => 427, 'email' =>'renato.vieira@uol.com.br'],			
['emailable_id' => 68, 'email' =>'augusto.c.mendes@terra.com.br'],			
['emailable_id' => 243, 'email' =>'zesouzamarques@gmail.com'],			
			
['emailable_id' => 484, 'email' =>'s-diniz@hotmail.com'],			
			
['emailable_id' => 117, 'email' =>'dl.cruz10@yahoo.com.br'],			
['emailable_id' => 387, 'email' =>'ocamposneto@gmail.com'],	['emailable_id' => 387, 'email' =>'oscar.aguiar@terra.com.br'],		
['emailable_id' => 252, 'email' =>'jjpmarc@hotmail.com'],			
			
			
			
			
['emailable_id' => 368, 'email' =>'miriam.garcia@uol.com.br'],			
['emailable_id' => 244, 'email' =>'jcrr02@bol.com.br'],			
['emailable_id' => 88, 'email' =>'c.l.de.medeiros@gmail.com'],			
['emailable_id' => 187, 'email' =>'alves.hermilo@gmail.com'],			
['emailable_id' => 299, 'email' =>'l.amartins@terra.com.br'],			
['emailable_id' => 80, 'email' =>'dleopoldolima@gmail.com'],			
['emailable_id' => 242, 'email' =>'pbjocs@gmail.com'],			
['emailable_id' => 298, 'email' =>'luuiiz2004@yahoo.com.br'],			
['emailable_id' => 335, 'email' =>'nuneschristina@gmail.com'],			
['emailable_id' => 399, 'email' =>'paulo.rescol@gmail.com'],			
['emailable_id' => 499, 'email' =>'valmirdalmas@gmail.com'],			
['emailable_id' => 285, 'email' =>'lucianocg@gmail.com'],			
['emailable_id' => 183, 'email' =>'heitorhsg@gmail.com'],			
['emailable_id' => 164, 'email' =>'fdanziato@yahoo.com.br'],			
['emailable_id' => 247, 'email' =>'jfscorrea@gmail.com'],			
['emailable_id' => 104, 'email' =>'cvfil.cvf@gmail.com'],			
['emailable_id' => 71, 'email' =>'bgmatos1@gmail.com'],			
['emailable_id' => 419, 'email' =>'rsstonini@gmail.com'],			
['emailable_id' => 169, 'email' =>'toninijr@gmail.com'],			
['emailable_id' => 279, 'email' =>'luceassis@uol.com.br'],			
['emailable_id' => 211, 'email' =>'joaoabc1@hotmail.com'],			
['emailable_id' => 395, 'email' =>'perivan@uol.com.br'],			
['emailable_id' => 26, 'email' =>'alfredoborba@gmail.com'],			
['emailable_id' => 514, 'email' =>'yukio.n@hotmail.com'],			
['emailable_id' => 337, 'email' =>'ferreiradelarocha@gmail.com'],			
['emailable_id' => 263, 'email' =>'jose.tenorio12@uol.com.br'],			
['emailable_id' => 350, 'email' =>'martinho.dabbadia@gmail.com'],			
['emailable_id' => 86, 'email' =>'cjfqueiroz@gmail.com'],			
['emailable_id' => 478, 'email' =>'srfgp@uol.com.br'],			
['emailable_id' => 405, 'email' =>'pslmattos@gmail.com'],			
['emailable_id' => 235, 'email' =>'siqueira.aloisio@gmail.com'],			
['emailable_id' => 209, 'email' =>'jesus.j.pereira@gmail.com'],			
['emailable_id' => 376, 'email' =>'neumarkribeiro@gmail.com'],			
['emailable_id' => 403, 'email' =>'probertol@uol.com.br'],			
['emailable_id' => 48, 'email' =>'anselmo.magalhaes@maxxlogbrasil.com.br'],			
['emailable_id' => 188, 'email' =>'hugoresendepaiva@gmail.com'],			
['emailable_id' => 349, 'email' =>'martaeba55@gmail.com'],			
['emailable_id' => 131, 'email' =>'marciammsouza@gmail.com'],			
['emailable_id' => 380, 'email' =>'norbarod@oi.com.br'],			
['emailable_id' => 90, 'email' =>'celestesa@uol.com.br'],			
['emailable_id' => 100, 'email' =>'cleidemedeiros2@hotmail.com'],			
['emailable_id' => 57, 'email' =>'eumario1@hotmail.com'],			
['emailable_id' => 352, 'email' =>'laynes@uol.com.br'],			
['emailable_id' => 406, 'email' =>'pasilvapereira1@gmail.com'],			
['emailable_id' => 333, 'email' =>'diasribeirocruz@gmail.com'],	['emailable_id' => 333, 'email' =>'dra.charmosa@gmail.com'],		
['emailable_id' => 99, 'email' =>'claudioalmeidaa@yahoo.com.br'],			
['emailable_id' => 206, 'email' =>'janetebastos22@yahoo.com.br'],			
['emailable_id' => 341, 'email' =>'mtereza03@gmail.com'],			
['emailable_id' => 305, 'email' =>'luizfsantos@gmail.com'],			
['emailable_id' => 288, 'email' =>'cggip.luciano@gmail.com'],			
['emailable_id' => 508, 'email' =>'wmsjr@terra.com.br'],			
['emailable_id' => 411, 'email' =>'railda@42cultural.com.br'],			
['emailable_id' => 414, 'email' =>'rai_figo@hotmail.com'],			
['emailable_id' => 138, 'email' =>'eron3007@gmail.com'],			
['emailable_id' => 291, 'email' =>'lualbertocosta@gmail.com'],			
['emailable_id' => 222, 'email' =>'jnlmacculloch1@gmail.com'],			
['emailable_id' => 325, 'email' =>'marcopaulo.pb@hotmail.com'],			
['emailable_id' => 355, 'email' =>'mauricio_pimentel@outlook.com.br'],			
['emailable_id' => 197, 'email' =>'ivaneidepassos@gmail.com'],			
['emailable_id' => 472, 'email' =>'selma.evangelista@hotmail.com'],			
['emailable_id' => 360, 'email' =>'miguelst@uol.com.br'],			
['emailable_id' => 436, 'email' =>'filipetro@terra.com.br'],			
['emailable_id' => 54, 'email' =>'ancale1@gmail.com'],			
['emailable_id' => 307, 'email' =>'luizhenriqueamorim@gmail.com'],			
['emailable_id' => 204, 'email' =>'jairgomes1@gmail.com'],			
['emailable_id' => 168, 'email' =>'geduso@ig.com.br'],			
['emailable_id' => 390, 'email' =>'calazans@gmail.com'],			
['emailable_id' => 124, 'email' =>'edsonm.sousa@hotmail.com'],			
['emailable_id' => 59, 'email' =>'ajprivas@gmail.com'],			
['emailable_id' => 296, 'email' =>'lmfdaniel@hotmail.com'],			
['emailable_id' => 37, 'email' =>'admiranda@gmail.com'],			
['emailable_id' => 381, 'email' =>'norio@conterp.com.br'],			
['emailable_id' => 426, 'email' =>'renatoscarv@yahoo.com.br'],			
['emailable_id' => 359, 'email' =>'andradefilho.miguel@gmail.com'],			
['emailable_id' => 475, 'email' =>'slucianofreire@gmail.com'],			
['emailable_id' => 487, 'email' =>'medradotania@yahoo.com'],			
['emailable_id' => 311, 'email' =>'manoel.esso@gmail.com'],			
['emailable_id' => 205, 'email' =>'janeamorim100@gmail.com'],			
['emailable_id' => 446, 'email' =>'robertochaves.rate@gmail.com'],			
['emailable_id' => 85, 'email' =>'carloshenrique@usilav.com.br'],	['emailable_id' => 85, 'email' =>'tmcalu26@gmail.com'],		
['emailable_id' => 118, 'email' =>'deniluz@gmail.com'],			
['emailable_id' => 477, 'email' =>'sergionham@gmail.com'],			
['emailable_id' => 67, 'email' =>'arturdultra@gmail.com'],			
['emailable_id' => 420, 'email' =>'rerigueira@gmail.com'],			
['emailable_id' => 1, 'email' =>'amj@abby.com.br'],			
['emailable_id' => 128, 'email' =>'elenitararaujo@gmail.com'],			
['emailable_id' => 232, 'email' =>'clinicasemo@hotmail.com'],			
['emailable_id' => 202, 'email' =>'jacquesrosat@gmail.com'],			
['emailable_id' => 323, 'email' =>'marcocaribe3@gmail.com'],			
['emailable_id' => 330, 'email' =>'mvteixeira@hotmail.com'],			
['emailable_id' => 21, 'email' =>'alexnovaisvieira@hotmail.com'],			
['emailable_id' => 302, 'email' =>'luizzup@hotmail.com'],			
['emailable_id' => 160, 'email' =>'fhoswald@gmail.com'],			
['emailable_id' => 378, 'email' =>'nilsoncunha@gmail.com'],			
['emailable_id' => 364, 'email' =>'miltonjb2009@hotmail.com'],			
['emailable_id' => 109, 'email' =>'dan.catalan2309@gmail.com'],			
['emailable_id' => 432, 'email' =>'ricardoengel@oi.com.br'],			
['emailable_id' => 328, 'email' =>'navaes@gmail.com'],			
['emailable_id' => 64, 'email' =>'aribeiro@gmail.com'],			
['emailable_id' => 147, 'email' =>'fgondimf@hotmail.com'],			
['emailable_id' => 347, 'email' =>'marival.mattos@gmail.com'],			
['emailable_id' => 14, 'email' =>'alberssan@hotmail.com'],			
['emailable_id' => 451, 'email' =>'rogeriaqo@hotmail.com'],			
['emailable_id' => 322, 'email' =>'marcoantonioamigo@yahoo.com.br'],			
['emailable_id' => 212, 'email' =>'joão.antonio.neto@terra.com.br'],			
['emailable_id' => 448, 'email' =>'robertorollin@gmail.com'],			
['emailable_id' => 265, 'email' =>'jgazevedo@outlook.com'],			
['emailable_id' => 452, 'email' =>'raf.2020@hotmail.com'],			
['emailable_id' => 167, 'email' =>'geilsonl@oi.com.br'],			
['emailable_id' => 293, 'email' =>'iurifaria@uol.com.br'],			
['emailable_id' => 409, 'email' =>'ralbuquerque9@uol.com.br'],			
['emailable_id' => 454, 'email' =>'ronaldo-ls@uol.com.br'],			
['emailable_id' => 417, 'email' =>'ranilsoncp@uol.com.br'],			
['emailable_id' => 251, 'email' =>'joseivanildoprazeresdeazevedoj@gmail.com'],			
['emailable_id' => 457, 'email' =>'rvirginio@uol.com.br'],			
['emailable_id' => 60, 'email' =>'miletto@gmail.com'],	['emailable_id' => 60, 'email' =>'miletto2021@gmail.com'],		
['emailable_id' => 126, 'email' =>'educakid8699@hotmail.com'],			
['emailable_id' => 494, 'email' =>'thomaswilliamh@gmail.com'],			
['emailable_id' => 431, 'email' =>'reyrizzo@terra.com.br'],			
['emailable_id' => 443, 'email' =>'roberto.morais10@gmail.com'],			
['emailable_id' => 306, 'email' =>'luizferradans@gmail.com'],			
['emailable_id' => 281, 'email' =>'luaribeiro@uol.com.br'],			
['emailable_id' => 39, 'email' =>'aplsampaio@uol.com.br'],			
['emailable_id' => 495, 'email' =>'tisufugi@gmail.com'],			
['emailable_id' => 154, 'email' =>'fairton@gmail.com'],			
['emailable_id' => 404, 'email' =>'psasampaio@gmail.com'],			
['emailable_id' => 303, 'email' =>'gozzini@hotmail.com'],			
			
['emailable_id' => 177, 'email' =>'goncalod.passos@outlook.com'],	['emailable_id' => 177, 'email' =>'gdpassos@hotmail.com'],		
['emailable_id' => 418, 'email' =>'raynonato1981@hotmail.com'],			
			
			
			
['emailable_id' => 101, 'email' =>'clelioviana@hotmail.com'],			
['emailable_id' => 151, 'email' =>'flavio.m.o@hotmail.com'],			
['emailable_id' => 82, 'email' =>'cedubran@gmail.com'],			
['emailable_id' => 297, 'email' =>'beto10spinola@gmail.com'],			
['emailable_id' => 34, 'email' =>'anavieira05@gmail.com'],			
['emailable_id' => 250, 'email' =>'josehumbert@uol.com.br'],			
['emailable_id' => 258, 'email' =>'zemariano335@gmail.com'],			
['emailable_id' => 375, 'email' =>'nlrs@terra.com.br'],			
['emailable_id' => 497, 'email' =>'ulysses_lino@yahoo.com'],			
['emailable_id' => 51, 'email' =>'kostasouza@gmail.com'],			
['emailable_id' => 489, 'email' =>'telmamrlins@gmail.com'],			
['emailable_id' => 490, 'email' =>'telma13corr@hotmail.com'],			
['emailable_id' => 490, 'email' =>'telma13corr@hotmail.com'],			
['emailable_id' => 152, 'email' =>'fcivatti@yahoo.com.br'],			
			
['emailable_id' => 36, 'email' =>'analuciav999@gmail.com'],			
['emailable_id' => 438, 'email' =>'ritadecassia.simoes@hotmail.com'],			
['emailable_id' => 210, 'email' =>'jo.amaro@terra.com.br'],			
['emailable_id' => 506, 'email' =>'wmgp2008@gmail.com'],			
['emailable_id' => 139, 'email' =>'etelvinotorres@outlook.com'],	['emailable_id' => 139, 'email' =>'guedestorres55@outlook.com'],		
['emailable_id' => 444, 'email' =>'roberto.gomes53@yahoo.com.br'],			
			
['emailable_id' => 201, 'email' =>'jacreisvilas@gmail.com'],			
['emailable_id' => 237, 'email' =>'souzajose2200@gmail.com'],	['emailable_id' => 237, 'email' =>'souzajose200@gmail.com'],		
['emailable_id' => 255, 'email' =>'jm-amorim@uol.com.br'],			
['emailable_id' => 319, 'email' =>'marciadearagao@hotmail.com'],			
['emailable_id' => 289, 'email' =>'lucidalvasaf@gmail.com'],			
['emailable_id' => 218, 'email' =>'soajc@uol.com.br'],	['emailable_id' => 218, 'email' =>'joaocezar5317@gmail.com'],		
['emailable_id' => 159, 'email' =>'ftitao@gmail.com'],			
['emailable_id' => 38, 'email' =>'amcerqueira.62@gmail.com'],			
['emailable_id' => 132, 'email' =>'eli95god@gmail.com'],			
['emailable_id' => 459, 'email' =>'roserosas23@gmail.com'],			
['emailable_id' => 52, 'email' =>'aclannes@uol.com.br'],			
['emailable_id' => 460, 'email' =>'rose_bastiao@hotmail.com'],			
['emailable_id' => 47, 'email' =>'annerosecoa@hotmail.com'],			
['emailable_id' => 413, 'email' =>'ray1111m@gmail.com'],			
['emailable_id' => 273, 'email' =>'kmsbarbosa@gmail.com'],			
['emailable_id' => 374, 'email' =>'nelsonaraujofilho@hotmail.com '],			
['emailable_id' => 439, 'email' =>'rcanuto56@hotmail.com'],			
['emailable_id' => 315, 'email' =>'marbaabram@gmail.com'],			
['emailable_id' => 344, 'email' =>'marildabrandao3@gmail.com'],			
['emailable_id' => 400, 'email' =>'prbda@hotmail.com'],			
['emailable_id' => 505, 'email' =>'vladimirqueiroz@ig.com.br'],	['emailable_id' => 505, 'email' =>'vqs0912@gmail.com'],		
['emailable_id' => 91, 'email' =>'celmario10@gmail.com'],			
['emailable_id' => 277, 'email' =>'licinio.resende@gmail.com'],			
['emailable_id' => 234, 'email' =>'acurcio@gmail.com'],	['emailable_id' => 234, 'email' =>'zeacurcio@me.com'],		
['emailable_id' => 173, 'email' =>'gilsfig@gmail.com'],			
['emailable_id' => 365, 'email' =>'msba.barbosa@yahoo.com.br'],	['emailable_id' => 365, 'email' =>'msba.menezes@outlook.com'],		
['emailable_id' => 55, 'email' =>'tonhodepa@hotmail.com'],	['emailable_id' => 55, 'email' =>'tonhodepa@gmail.com'],		
['emailable_id' => 203, 'email' =>'jaimecfp@gmail.com'],			
['emailable_id' => 227, 'email' =>'joaquim.alex@yahoo.com.br'],			
['emailable_id' => 270, 'email' =>'mota.juvenal@gmail.com'],			
['emailable_id' => 329, 'email' =>'mvlads@hotmail.com'],			

    

    
];

?>

